pack.description=§bポケリエでっしゃら

intro########################################

welcome.oak=やあ
serp.intro_start=【ポケリエ_Aホウエン地方】
serp.choosing_gen=どれを選ぶ？
serp.choosing_poke=どのポケモンにするのじゃ？
serp.gen_forget=ポケリエ_Aホウエン地方
serp.intro_end=ポケモンとの旅の始まりだ
serp.fatal_damage=はまた1つ近づいた…
serp.healed=ポケモン達が全回復した！
joy.1=赤ちゃんすきぃ？赤ちゃん…
joy.2=フレッシュミントたまらねええええええ！！
joy.3=スピアー最強！スピアー最強！
joy.4=ミスティックミント
joy.5=パワーミントキマりますわ〜!!
jenny.1=はい
jenny.2=ダーリンダンス
jenny.3=ギャハハ！
jenny.4=1919
jenny.5=あにょはぜよ
event.2=はい
event.3=にょ、にょまれ〜
serp.gen1=Aホウエン図鑑
serp.gen2=Aホウエン図鑑2
serp.gen3=Aホウエン図鑑3
serp.gen4=Aホウエン図鑑4
serp.gen5=???
serp.summon=君に決めた！
serp.growl=鳴かせる
serp.radar=色違い率をあげる

Store#######################################

store.sold=売却した
store.buy=購入した
store.dont_have_money=金がないのに買おうとするなよ、はんじょう！
store.dont_have_this=お前はこれを買う価値無し
store.category=どのカテゴリーを選びますか？
store.balls=ボール系統
store.potions=キズぐすり系統
store.items=アイテム系統
store.clothing=ぼうぐ系統
store.tm=わざマシン系統
store.sell=アイテムを売る
tm.body=持ってる数: 
trader.body=ポケモン交換

jenny.category=ここではポケリエに関するイベントや情報を見る事ができます
jenny.cat0=プレイヤーアイテム
jenny.cat1=進化アイテム
jenny.cat2=ヌシポケモン
jenny.cat3=ポケモンジム
jenny.cat4=イベント情報
jenny.cat5=アップデート情報
jenny.cat6=伝説・幻のポケモン

jenny.body0=ポケリエには様々なアイテムがあります、ここではプレイヤーに関するアイテムの一部を説明します。\n\n-どくどくだま: 持つと即時にダメージを受けていき、リスポーン地点まで戻ることが出来ます。\n\n-ちゃくちパック: ホットバーに持っていると落下耐性が付き、落下ダメージを無効にします。\n\n-しんそくスカーフ: ホットバーに持っていると移動速度が上昇します。\n\n-すいちゅうのおまもり: ホットバーに持っていると水中呼吸が付き、水中でも呼吸が可能になります。\n\nこれらのアイテムは行商人との交換やクラフトで入手可能です。
jenny.body1=アイテムを使うことで進化するポケモンもいます。\n-あらゆる進化のアイテムは「ポケモンに使う」ことで効果を発揮する、いずれの道具もポケモンを進化させると消費される。\n\n-入手方法:進化アイテムは取り引き、クラフトする事で入手が可能です。\n\n-使用できるポケモンの例:コソクムシが〈こおりのいし〉でムショウグン,ジュラルドンが〈ふくごうきんぞく〉でブリジュラスなど
jenny.body2=全6つのバイオームには〈ヌシポケモン〉が存在します。ヌシポケモンを倒すと〈ひでんスパイス〉や〈モニュメント〉などが落ちることがあります。\n\n-ヌシポケモンがいるバイオーム一覧\n-森林バイオーム\n-砂漠バイオーム\n-サバンナバイオーム\n-沼地バイオーム\n-海バイオーム\n-ネザー\n-ザ・エンド
jenny.body3=-ポケモンジムについて\n-この世界には〈全18タイプ〉のジムがあります。ジムを1つクリアするとショップの商品が3割引きされて安く買う事が出来るようになります。\n\n-詳しくはポケモンセンターのチェストにある本をご確認ください。
jenny.body4=現在のイベント情報はありません
jenny.body5=現在のバージョンは:ver1.0 です
jenny.body6=§r
serp.main.tm_machine.list=ニックネーム変更

Mission#####################################

communicator.selector=ロトム通話機
communicator.body=誰に電話する？
communicator.trade=少年マイケル
communicator.analyze=センチネル博士
communicator.legendary=黄猿
communicator.trainer=んんんんんんモォクロオォォォオオオ!!!
trainer.thanks=これあげるぜぽよ
communicator.prof=にょっす！
prof.mega=メガストーンだねこれ早く受け取れ
prof.dynamax=ねがいぼし！？な、なにぃ！？これに変えてあげるから使ってみなさい
prof.egg=割れてる卵じゃのう、それじゃあ新しい卵変えてあげるのです。もしかしたらモクローとかモクローとかモクローとかモクローとかモクローとかモクローとかモクローが出るかものう
combat.mechanic0=§r
combat.mechanic1=パワーブーストを発動！発動中は相手に与えるダメージが1.2倍になります 残りターン数:
mission.legendary=ヘイラッシャ！
communicator.goh=にょっす！だねぇ〜
goh.articuno=フリーザーだねぇ〜わっしは1番好きだねぇぇぇ、、、はいこれ使いな
goh.zapdos=サンダーだ！おめでとう！君は本当に天才で凄いよ！！！これと交換してあげる！
goh.moltres=あっはいどうぞ
goh.raikou=ライコウ！？本当かい！？あなたはとことん化け物じみてるねぇぇぇ。天才のさらに上ロギアよりもさらにキショ…
goh.entei=エンティだねはい
goh.suicune=水の君主いいねぇぇぇどー

combat.trainer=トレーナーorバトル
combat.wild=野生
combat.challenged=あなたのポケモンが勝負を挑まれています
combat.used= 使用
combat.max_transformed=攻撃！
combat.cant_change_status=状態異常には ならなかった！

Battle######################################

item.serp:apricorn_seed.name=ぼんぐりの種
serp.vial_reloaded=クイックヒール の バッテリー が 充電された！
serp.vial_healed=§gクイックヒール きのうに より ポケモンたちが かいふくした！§f残り使用回数: 
combat.used= の
combat.level= レベル 
combat.expup= けいけんち
combat.exp_share=がくしゅうそうちで 手持ち全員のポケモンにも経験値が貰えた！
combat.received= に
combat.receivedd= 受け取りました §l§c 
combat.receivedm= 受け取りました §l§d 
combat.you_received= 勝利して 賞金を受け取った！: 
combat.damage=ダメージ！
combat.challenge1= §rもしグソクムシャすこすこから自認梢=すこムシャモスキートになって花帆さんの「こじゅえせんぱい〜♡」梢さん「花帆、その呼び方はやめてちょうだい。」みたいにすこすこ「ムシャせんぱい〜♡」グソクムシャさん「ムシャ、その刑務所みたいな呼び方はやめてちょうだい」ってグソクムシャさんの事を自認梢で呼び始めたらどう思う？
combat.challenge2= §6すこすこ、「832028」よ
combat.challenge3= §rすこすこ「まだだ、いや…あいつはもう…」ルガルガン「俺らがやる、後は任せろ」ぺリッパー「俺が雨を降らし」オクタン「ボク達が」グソクムシャ「頑張ろうよっ！」ネイティオ「おう！」すこすこ「グソクムシャすこ軍団は 目覚め 俺の力はブロリー状態 まるで… 今までの弱さは 嘘だったのように 追風は 我々を包み込み そのまま 俺の指は アンドロメダを指していた──」
combat.challenge4= §bなんですかなんですか
combat.challenge5= §bまるで白昼夢を見てるようでした。
combat.challenge6= §gおっはパパイヤ
combat.challenge7= §cおっはチャーシュー麺
combat.challenge8= §eちぇすとー！！！！！
combat.challenge9= §a行きますよ、ほにゃらら戦法！
combat.challenge10= §fこずーえいつもありがとう！最近こずーえへ感謝するのが日課になりつつあります！単刀直入に我慢してたこと書いちゃう！こずーえ愛してるぞおおおお(ps.厄介蓮ノ空のことモクすこクラブだと思われてそうですが長文赤スパ失礼！ちなみに読まれてる頃にはあまりの恥ずかしさにユニバーサル大回転ホリデーホリデーの舞₍ ◝(‘ω’)◟ ⁾⁾₍₍ ◝(‘ω’)◜ ₎しながらベッドの上で暴れていると思うので率直な一言もらってもいいですか？w最後に一言！配信をはじめ本当にいつもありがとう！！蓮ノ空のことモクすこクラブ達を大切に思ってくれる姿勢冗談抜きで本当に好きです。応援するしがいがあります！
combat.challenge11= §rすこ「くさ・ひこうなんて全身がジジイの歯みたいなボロボロのタイプは糞喰らえだね。」
combat.challenge12= §g虹花シンゴリファー
combat.challenge13= §gレッツダンシングソクムシャ！ずんどこずんどこ！
combat.challenge14= §b急急如律令！
combat.challenge15= §dエヴォニー オブ ワンズ
combat.challenge16= §rこずーえに、告白しようと思ってる。スレのみんなには、悪いけど。抜け駆けで。次の給料日、お金入るから。スパチャして。そこで気持ち伝える。こずーえは男の人と付き合ったことないから。びっくりするかもだけど。もう気持ちを伝えるのを我慢できないから。
combat.challenge17= §cラベンダー オブ ワンズ
combat.challenge18= §d俺にコンボイさせてくれよ
combat.challenge19= §cはい、答え合わせ！
combat.challenge20= §g皇国アリスマティック
combat.challenge21= §cアイボリー オブ ペンタクルス
combat.challenge22= §bあなたはお姉ちゃんみたいなすごい人なんだなって気付いたよ。これからも、私の力になってね！
combat.challenge23= §a【すこす構文とは】〈通称 グソクムシャすこすこ〉の「…なのだけれど」と言った特徴的な言い回し。転じてそれがミームとして流行り始めたネット構文。
combat.challenge24= §cあれ？w予想通りすぎるんだけどw
combat.challenge25= §bスノウドロップ オブ カップス
combat.seriously_poisoned=毒ダメージやん
combat.poisoned= が毒でダメージを受けている
combat.badly_poisoned= が猛毒だ
combat.sleeping= は眠っている
combat.sleepy= は眠い
combat.frozen= は凍っている！
combat.confused= は混乱している！
combat.cured= は状態異常が治った！
combat.critic= 急所に当たった！
combat.flinch= は怯んだ！
combat.status1= は まひで うごけない…
combat.status2= は やけど で ダメージをうけている…
combat.status3= は どく で ダメージをうけている…
combat.status4= は もうどく で ダメージをうけている…
combat.status5= は ねむっていて うごけない…
combat.status6= は ねむっていて うこけない…
combat.status7= は こおっていて うごけない…
combat.status8= は こんらんしている…
combat.sleepy=疲れていて動けない…
combat.frozen=凍ってて動けない！
combat.paralyzed_release= まひが なおった
combat.burned_release= やけどが なおった
combat.burned=はやけどだ
combat.slept_release= 目が覚めた
combat.sleepy_release= の攻撃で眠らなくなった
combat.frozen_release= の攻撃で凍らなくなった
attack.cold_release= の攻撃で凍らなくなった
combat.awaken= 目が覚めた！
combat.sleepless=眠り無効
combat.lying=疲れ果てて眠った
combat.defrost=氷が熔けた
combat.not_received=ダメージを受けなかった
combat.ineffective=こうかは いまひとつだ…
combat.immunity=こうかがない ようだ…
combat.miss=こうげきは あたらなかった！
combat.effective=こうかは ばつぐんだ！
combat.critic=きゅうしょ にあたった！
combat.happiness_critic=友情により急所に当たった
combat.happiness.released=友情により下がった能力と状態異常が回復した
combat.cooldown =わざのはんどうで うごけない！
combat.retroceded= ひるんだ！
combat.atk_increased=攻撃が上がった
combat.atks_increased=特攻が上がった
combat.def_increased=防御が上がった
combat.defs_increased=特防が上がった
combat.spd_increased=素早さが上がった
combat.atk_cant_increase=もう攻撃はあがらない
combat.atks_cant_increase=もう特攻は上がらない
combat.def_cant_increase=もう防御は上がらない
combat.defs_cant_increase=もう特防はあがらない
combat.spd_cant_increase=もう素早さはあがらない
combat.atk_cant_reduce=もう攻撃は下がらんけんね
combat.atks_cant_reduce=もう特攻は下がらんけん
combat.def_cant_reduce=もう防御は下がらんけん
combat.defs_cant_reduce=もう特防は下がらんけん
combat.spd_cant_reduce=もうすばやさは下がらんけん
combat.atk_reduced=攻撃が下がったのだ 
combat.atks_reduced=特攻が下がってら
combat.def_reduced=防御が下がった
combat.defs_reduced=特防が下がったのじゃ
combat.speed_reduced=素早さ低下 
combat.spd_reduced=素早さ低下 
combat.accuracy_increased=命中率が上がった
combat.evs_increased=回避率が上がった 
combat.evasion_increased=回避率が上がった
combat.accuracy_cant_increase=命中率はもう上がらない
combat.evs_cant_increase=回避率はもう上がらない
combat.accuracy_reduced=命中率が下がった
combat.evs_reduced=回避率が下がった
combat.evasion_increased=回避率が上がった 
combat.cure=じょうたいいじょう がなおった！
combat.nothing_prepared= ？
combat.challenge_legendary= とてつもなく強敵の予感がする…
combat.booster_prepared=ブースター！
combat.mega_prepared= メガシンカ可能
combat.max_prepared= ダイマックス可能
combat.win=勝負に勝った
combat.levelup=レベルアップ！
trainer.pre1=§r
trainer.pre2=§r
trainer.pre3=§r
trainer.battle1=§r
trainer.battle2=§r
trainer.battle3=§r
trainer.lose1=§r
trainer.lose2=§r
trainer.lose3=§r
trainer.surrender1=§r
trainer.surrender2=§r
trainer.surrender3=§r
trainer.end1=§r
trainer.end2=§r
trainer.end3=§r
trainer.finish1=§r
trainer.finish2=§r
trainer.finish3=§r
enemy.pre1=§r
enemy.pre2=§r
enemy.pre3=§r
enemy.battle1=§r
enemy.battle2=§r
enemy.battle3=§r
enemy.lose1=§r
enemy.lose2=§r
enemy.lose3=§r
enemy.surrender1=§r
enemy.surrender2=§r
enemy.surrender3=§r
enemy.end1=§r
enemy.end2=§r
enemy.end3=§r
enemy.finish1=§r
enemy.finish2=§r
enemy.finish3=§r
serp.pokedex_register= が図鑑に登録されました！
serp.poi.title=ポケモンセンターへ戻る
serp.poi.confirm=最後に行ったポケモンセンターへ戻りますか？

 apricorn####################################

item.null.name=なし
item.serp:pokedex.name=ポケモン図鑑
item.serp:apricorn_red.name=あかぼんぐり
item.serp:apricorn_blue.name=あおぼんぐり
item.serp:apricorn_white.name=しろぼんぐり
item.serp:apricorn_yellow.name=きいろぼんぐり
item.serp:apricorn_black.name=くろぼんぐり
item.serp:apricorn_green.name=みどりぼんぐり
item.serp:apricorn_cyan.name=みずいろぼんぐり
item.serp:apricorn_pink.name=ピンクぼんぐり
item.serp:apricorn_orange.name=オレンジぼんぐり
item.serp:sweet_applee.name=§aすっぱいりんご
item.serp:return.name=§bナイトビションロッド\n\n§o§7オフハンドに持つと、20分間暗視効果が付与される。
item.serp:pokedoll_lickitung_shiny.name=§eぺろぺろぬいぐるみ
item.serp:pokeuc.name=§dレインボープレミアムアトリチケット
item.serp:dynamax_candy.name=§e楽園の王冠\n\n§o§7[Oracle Étude]モクローを介入できる王冠\n\nようこそ、来訪者\nElysionへの良い旅路を。
item.serp:kus.name=§aクスリソウ\n\n§o§7色々なクラフト素材
item.serp:kusp.name=§aクスリ水\n\n§o§7クスリソウを調造することで入手できるクラフト素材
item.serp:pe.name=§gピーピーグサ\n\n§o§7色々なクラフト素材
item.serp:tub.name=§eゲンキノツボミ\n\n§o§7色々なクラフト素材
item.serp:e_k.name=§lレジドラゴの鍵
item.serp:kapb.name=§a守り神のお供え物・木【解放:カプ・ブルル】
item.serp:kapc.name=§e守り神のお供え物・雷【解放:カプ・コケコ】
item.serp:sword.name=§bくちたけん【解放:ザシアン】
item.serp:shield.name=§cくちたたて【解放:ザマゼンタ】
item.serp:eve.name=§bポケリエガチャチケット\n\n§o§7ポケリエガチャを引くことが出来るチケット
item.serp:ribra.name=§aリブラのイヤリング
item.serp:raira.name=§bライラの邪悪な目
item.serp:clearb.name=§gとうめいなスズ\n\n§o§7こころ やすまる 音色が きける とても ふるめかしい スズ

Items#######################################
item.serp:max_elixir.name=§bピーピーマックス\n\n§o§7ポケモンのPPをすべて全回復させる。
item.serp:rowlet.name=§aモクローすこすこドール
item.serp:rowlet_shiny.name=§eレアモクローすこすこドール
item.serp:ancient_amber.name=§gひみつのコハク\n\n§o§7復元することが出来る古代の化石
item.serp:mew_dna.name=§dミュウの遺伝子
item.serp:raikou_lock.name=嘶く皇の鬣
item.serp:entei_lock.name=穿つ帝の鬣
item.serp:suicune_lock.name=畝る君主の鬣
item.serp:raikou_offering.name=皇の掛け軸
item.serp:entei_offering.name=帝の掛け軸
item.serp:suicune_offering.name=君主の掛け軸
item.serp:exp_share.name=§gがくしゅうそうち\n\n§o§7被ると控えのポケモンに獲得した経験値の半分、分けられる。
item.serp:dynamax_band.name=ダイマックスバンド
item.serp:revive.name=げんきのかけら\n\n§o§7ポケモンをHP半分で復活させる
item.serp:max_revive.name=げんきのかたまり\n\n§o§7ポケモンをHP満タンの状態で復活させる
item.serp:repel.name=シャインスプレー\n\n§o§7使用後、5分間色違いが出る確率×1.5倍
item.serp:super_repel.name=シルバーシャインスプレー\n\n§o§7使用後、10分間色違いが出る確率×1.5倍
item.serp:max_repel.name=ゴールドシャインスプレー\n\n§o§7使用後、10分間色違いが出る確率×2倍
serp.pokedex=ポケモンブック
serp.pokemon=ポケモン
pokedex.data=ポケモン図鑑
item.serp:mulch.name=怪しい肥料
item.serp:linking_cord.name=つうしんケーブル
item.serp:poke_ride.name=ライドギア\n\n§o§7ポケモンに乗ることが出来るようになる装置。
item.serp:rare_candy.name=ふしぎなアメ\n\n§o§7ポケモンのレベルを1上げる不思議な飴。
item.serp:poke.name=ポケコイン
item.serp:fluffy_tail.name=くすぐり道具
item.serp:poke_toy.name=いんせき
item.serp:key_shard_natural.name=メガ水晶
item.serp:key_shard_processed.name=メガストーンの欠片
item.serp:key_stone.name=メガストーン
item.serp:mega_ring.name=メガバングル
item.serp:mega_ring_empty.name=石なしメガバングル
item.serp:gift.name=§cギフトブースター\n\n§o§7ホットバーにあると採掘速度が1.2倍になる
item.serp:gifts.name=§bギフトブースターII\n\n§o§7ホットバーにあると採掘速度が1.6倍になる
item.serp:giftp.name=§bギフトブースターIII\n\n§o§7ホットバーにあると採掘速度が???倍になる 
item.serp:casi.name=カジノコイン\n\n§o§7カジノで必要なコイン
item.serp:kodai.name=§d宇宙バッジ\n\n§o§7持っていると特別なイベントが解放されるバッジ
item.serp:stan.name=§bブルームスター
item.serp:berry_seeds.name=きのみの木の種
item.serp:poke_ore.name=煌めく鉱石
item.serp:mt_ore.name=わざマシンストーン
item.serp:key_ore.name=わざマシン鉱石
item.serp:wish_ore.name=ねがい隕石
item.serp:wishing_star.name=ねがいぼし
item.serp:bad_egg.name=割れたまご
item.serp:pokemon_egg.name=なにかのたまご\n\n§o§7孵化装置に入れるとポケモンやMPLが生まれる。
item.serp:bike_pass.name=バイクチケット
item.serp:ride_pass.name=ライドパス
item.serp:clothing_ticket.name=レジェンドチケット
item.serp:kin.name=ぎんのおうかん
item.serp:oga.name=§aみどりのめん【解放:オーガポン】
item.serp:gi.name=§6リブラのモニュメント
item.serp:hi.name=§dライラのモニュメント
item.serp:neku.name=§dコズミックストーン\n\n§o§7ウルトラネクロズマを呼び出せる石

Suits#######################################

combat.cursed_body_locked=【のろわれボディ】の影響でわざを使えない！
item.serp:ash_helmet.name=頭
item.serp:ash_chestplate.name=鎧
item.serp:ash_leggings.name=アイツのズボン
item.serp:ash_boots.name=あいつの靴
item.serp:red_helmet.name=あいつの頭
item.serp:red_chestplate.name=あいつの胸
item.serp:red_leggings.name=あいつのパンツ
item.serp:red_boots.name=あいつの靴
item.serp:green_helmet.name=緑の頭
item.serp:green_chestplate.name=緑の胸
item.serp:green_leggings.name=緑のズボン
item.serp:green_boots.name=緑の靴
item.serp:rocket_helmet.name=黒服の帽子
item.serp:rocket_chestplate.name=黒服のお胸
item.serp:rocketm_leggings.name=黒服のズボン
item.serp:rocketf_leggings.name=黒服のスカート
item.serp:rocket_boots.name=黒服の靴
item.serp:lea.name=§aピルエットミント\n\n§o§7色々なクラフト素材
item.serp:shiro.name=§eホワイトミント\n\n§o§7色々なクラフト素材
item.serp:articuno_feather.name=§b淡めく羽根
item.serp:zapdos_feather.name=§g嘶く羽根
item.serp:moltres_feather.name=§c燃の羽根
item.serp:articuno_offering.name=氷鳥の王冠【解放:フリーザー】
item.serp:zapdos_offering.name=雷鳥の王冠【解放:サンダー】
item.serp:moltres_offering.name=炎鳥の王冠【解放:ファイヤー】

Balls#######################################

item.serp:pokeball.name=モンスターボール\n§7捕獲率×1.0
item.serp:greatball.name=スーパーボール\n\n§o§7(捕獲率×1.5)
item.serp:ultraball.name=ハイパーボール\n\n§o§7(捕獲率×2.0)
item.serp:masterball.name=§dマスターボール\n\n§o§7(捕獲率×255)
item.serp:beastball.name=§1ウルトラボール\n\n§o§7(捕獲率×0.1)
item.serp:diveball.name=ダイブボール\n\n§o§7(捕獲率×1.0,水中で使用時:×3.0)
item.serp:dreamball.name=§dドリームボール\n\n§o§7(捕獲率×1.0,眠り時:×3.0)
item.serp:duskball.name=ダークボール\n\n§o§7(捕獲率×1.0,夜時:×3.0)
item.serp:fastball.name=§6ファストボール\n\n§o§7(捕獲率×1.0,素早さが高いポケモン:×5.0)\n連射倍率×10
item.serp:friendball.name=§aフレンドボール\n\n§o§7(捕獲率×1.0,捕獲時になつきやすい)
item.serp:healball.name=ヒールボール\n\n§o§7(捕獲率×1.0,捕獲時にポケモンのHP全回復)
item.serp:heavyball.name=§bヘビー§rボール\n\n§o§7捕獲率×1.0,重いポケモン:×5.0\n連射倍率×0.05
item.serp:lureball.name=§bルアーボール\n\n§o§7(捕獲率×1.0,水中で使用時:×3.0)
item.serp:luxuryball.name=ゴージャスボール\n\n§o§7(捕獲率×1.0,捕獲時になつきやすい)
item.serp:moonball.name=§bムーン§eボール\n\n§o§7(捕獲率×1.0,月が三日月に近いほど上昇:最大×10.0)
item.serp:nestball.name=ネストボール\n\n§o§7(捕獲率×1.0,相手のレベルが低いほど上昇:×5.0)
item.serp:netball.name=ネットボール\n\n§o§7(捕獲率×1.0,むしorみずタイプに:×3.0)
item.serp:parkball.name=§eパークボール\n\n§o§7(捕獲率×5.0)
item.serp:premierball.name=プレミアボール\n\n§o§7(捕獲率×1.5)
item.serp:safariball.name=§aサファリボール\n\n§o§7(捕獲率×2.0)
item.serp:cherishball.name=§cプレシャスボール§r\n\n§o§7(捕獲率×1.0)
item.serp:levelball.name=§6レベルボール\n\n§o§7(捕獲率×1.0,相手のレベルが低いほど捕獲率上昇:最大3倍)
item.serp:loveball.name=§dラブラブボール\n\n§o§7(捕獲率×1.0,相手ポケモンと性別が違うと捕獲率2倍)
item.serp:strangeball.name=§aストレンジボール§r\n\n§o§7(捕獲率×3.0)
item.serp:sportball.name=§6コンペボール\n\n§o§7(捕獲率×1.0)
item.serp:repeatball.name=リピートボール\n\n§o§7(捕獲率×1.0,既に捕まえた事があるポケモンの捕獲率×5.0)
item.serp:quickball.name=§eクイック§bボール\n\n§o§7(捕獲率×1.0,最初のターンに投げると捕獲率×5.0)
item.serp:timerball.name=タイマーボール\n\n§o§7(捕獲率×1.0,バトルターンが経過するほど上昇:×5.0)
item.serp:pokec.name=§bカジノコイン引き換え券\n\n§o§7カジノコイン10枚と引き換えができる
item.serp:pokerc.name=§eキラアトリチケット
item.serp:badge.name=§6ポケバッジ\n\n§o§7わざマシン作成や取引に使える
item.serp:serina.name=§dヒールエネルギーチップ\n\n§o§7クラフトに使える素材
item.serp:nizu.name=§dナ§bナ§aイ§cロ§gイ§dン§bゴ§aッ§cト
item.serp:herb.name=§aリフレッシュハーブ\n\n§o§7
item.serp:sdia.name=§bエンデュランスシード\n\n§o§7色々なクラフトに使える素材
item.serp:ca.name=§cちからのコイン\n\n§o§7攻撃が高いポケモンが落とすクラフト素材のコイン
item.serp:cb.name=§bぼうぎょのコイン\n\n§o§7防御が高いポケモンが落とすクラフト素材のコイン
item.serp:cc.name=§gちえのコイン\n\n§o§7特攻が高いポケモンが落とすクラフト素材のコイン
item.serp:cd.name=§6せいしんのコイン\n\n§o§7特防が高いポケモンが落とすクラフト素材のコイン
item.serp:ce.name=§aすばやさのコイン\n\n§o§7素早さが高いポケモンが落とすクラフト素材のコイン
item.serp:cf.name=§dたいりょくのコイン\n\n§o§7体力が高いポケモンが落とすクラフト素材のコイン
item.serp:ck.name=§gレジェンドコイン\n\n§o§7クラフトで作れるクラフト素材のコイン
item.serp:ba.name=§cネザーのモニュメント\n\n§o§7ネザーのヌシポケモンがたまに落とすクラフト素材
item.serp:bb.name=§b海のモニュメント\n\n§o§7海のヌシポケモンがたまに落とすクラフト素材
item.serp:bc.name=§a森林のモニュメント\n\n§o§7森林のヌシポケモンがたまに落とすクラフト素材
item.serp:bd.name=§g砂漠のモニュメント\n\n§o§7砂漠のヌシポケモンがたまに落とすクラフト素材
item.serp:be.name=§6サバンナのモニュメント\n\n§o§7サバンナのヌシポケモンがたまに落とすクラフト素材
item.serp:bf.name=§d沼地のモニュメント\n\n§o§7沼地のヌシポケモンがたまに落とすクラフト素材
item.serp:bk.name=§c伝§b説§aの§eモ§dニ§gュ§cメ§bン§aト\n\n§o§7伝説級のヌシポケモンがたまに落とすクラフト素材
item.serp:cheri.name=§gアドバンス§dチェリー\n\n§o§7上位のアイテムをクラフトするのに必要なチェリー\nトワイライト地方の名産品
item.serp:bk.name=§c伝§b説§aの§eモ§dニ§gュ§cメ§bン§aト\n\n§o§7伝説級のヌシポケモンがたまに落とすクラフト素材
item.serp:kure.name=§aクレソン\n\n§o§7苦味が 強い 食材。\n独特のクセが 特徴の野菜。\nやや好みが 分かれる 食材だ
item.serp:tomato.name=§cトマトスライス\n\n§o§7酸味が 強い 食材。\nうま味の成分を 多く 含んでいるので\nいろんなポケモンに 人気なのだ
item.serp:retasu.name=§gきパプリカスライス\n\n§o§7苦味が ある 食材。\n赤いパプリカと 味の差は 特にないが\nミックスして 使えば 目にも おいしい
item.serp:ham.name=§dハムスライス\n\n§o§7塩味が 強い 食材。\nしっかりとした 塩味 あるので\n野菜類と 非常に 相性がよい
item.serp:piman.name=§aピーマンスライス\n\n§o§7苦味が ある 食材。\nスライスして サンドイッチに\nはさめば アクセントに なる
item.serp:avo.name=§dアーリーレッド\n\n§o§7甘味が 強い 食材。\nたまねぎと 比較して 辛味や 香りが\n穏やかで 食べやすい
item.serp:spa.name=§cひでん:からスパイス\n\n§o§7珍しいアイテムのクラフトやサンドイッチに必要とするスパイス
item.serp:spb.name=§eひでん:すぱスパイス\n\n§o§7珍しいアイテムのクラフトやサンドイッチに必要とするスパイス
item.serp:spc.name=ひでん:しおスパイス\n\n§o§7珍しいアイテムのクラフトやサンドイッチに必要とするスパイス
item.serp:spd.name=§aひでん:にがスパイス\n\n§o§7珍しいアイテムのクラフトやサンドイッチに必要とするスパイス
item.serp:spe.name=§dひでん:あまスパイス\n\n§o§7珍しいアイテムのクラフトやサンドイッチに必要とするスパイス
item.serp:sandw.name=§6ベースサンドイッチ\n\n§o§7色んなサンドイッチの元となる元のサンドイッチ
item.serp:sandwf.name=§6ジムサンドイッチ\n\n§o§7フェアリージムのジムチャレンジ用のサンドイッチ
item.serp:sandwu.name=§6ウルトラサンドイッチ\n\n§o§7エンドでウルトラビーストを呼び出せるサンドイッチ
item.serp:sandwr.name=§6ファンタジーサンドイッチ\n\n§o§7幻のポケモンを呼び出せるサンドイッチ
item.serp:sandwc.name=§gシオンコイン\n\n§o§71000円で売却できるコイン\n\n翔音地方だと500円だが、それ以外の地方では価値が少し高い
item.spawn_egg.entity.pa:wandering_trader.name=ヨワナスポーンエッグ
entity.pa:wandering_trader.name=ヨワナ
entity.pa:wandering_traders.name=色違いのヨワナ
entity.pa:golisopede_mega.name=§6プロローグ§r

Ball Parts##################################

item.serp:down_part.name=ボールダウンパーツ\n\n§o§7ボールをクラフトするための素材
item.serp:pokeball_up.name=モンスターボールの欠片
item.serp:greatball_up.name=スーパーボールの欠片
item.serp:ultraball_up.name=ハイパーボールの欠片
item.serp:diveball_up.name=ダイブボールの欠片
item.serp:dreamball_up.name=ドリームボールの欠片
item.serp:duskball_up.name=ダークボールの欠片
item.serp:fastball_up.name=ファストボールの欠片
item.serp:friendball_up.name=フレンドボールの欠片
item.serp:healball_up.name=ヒールボールの欠片
item.serp:heavyball_up.name=ヘビーボールの欠片
item.serp:lureball_up.name=ルアーボールの欠片
item.serp:luxuryball_up.name=ゴージャスボールの欠片
item.serp:moonball_up.name=ムーンボールの欠片
item.serp:nestball_up.name=ネストボールの欠片
item.serp:netball_up.name=ネットボールの欠片
item.serp:parkball_up.name=パークボールの欠片
item.serp:premierball_up.name=プレミアボールの欠片
item.serp:safariball_up.name=サファリボールの欠片
item.serp:timerball_up.name=タイマーボールの欠片
item.serp:sta.name=§cあかいたまいし\n\n§o§7モンスターボールのクラフト素材。
item.serp:stb.name=§bあおいたまいし\n\n§o§7モンスターボールのクラフト素材。
item.serp:stc.name=§gくろのたまいし\n\n§o§7モンスターボールのクラフト素材。
item.serp:staa.name=§cレッドクリスタル\n\n§o§7焼くことでたまいしになるクリスタル。
item.serp:stbb.name=§bブルークリスタル\n\n§o§7焼くことでたまいしになるクリスタル。
item.serp:stcc.name=§gブラックリスタル\n\n§o§7焼くことでたまいしになるクリスタル。
tile.serp:sta_block.name=§cレッドクリスタルストーン
tile.serp:stb_block.name=§bブルークリスタルストーン
tile.serp:stc_block.name=§gブラックリスタルストーン
tile.serp:sta_bricks.name=§cレッドクリスタルレンガ
tile.serp:stb_bricks.name=§bブルークリスタルレンガ
tile.serp:stc_bricks.name=§gブラックリスタルレンガ
tile.serp:sta_poke.name=§cレッドポケスタル
tile.serp:stb_poke.name=§bブルーポケスタル
tile.serp:stc_poke.name=§gブラックポケスタル
tile.serp:gilded_chest.name=§cシルクタッチで取らないでね
tile.serp:yellow_gilded_chest.name=§cシルクタッチで取るな
tile.serp:fire_block.name=§cフレイムストーンブロック
tile.serp:water_block.name=§bウォーターストーンブロック
tile.serp:leaf_block.name=§aリーフストーンブロック
tile.serp:thunder_block.name=§eサンダーストーンブロック
tile.serp:moon_block.name=§dムーンストーンブロック
tile.serp:sun_block.name=§cサンストーンブロック
tile.serp:ice_block.name=§bアイスストーンブロック
tile.serp:shiny_block.name=§eシャイニーストーンブロック
tile.serp:dusk_block.name=§dダークストーンブロック
tile.serp:mesame_block.name=§bエンシェントストーンブロック
tile.serp:f_leaves.name=§aヒールポケリーフ

Stones######################################

item.serp:rotomarket.name.name=§gロトムマーケット\n\n§o§7置くことでどこでもショップを開ける
item.serp:tm_machine.name=§gわざマシンマシンマシマシ\n\n§o§7置くことでわざマシンにデータを入れられる
item.serp:sui.name=§c赤のポケ書(10)\n\n§o§7ショップで売ることが出来る売却アイテム
item.serp:sub.name=§b青のポケ書(40)\n\n§o§7ショップで売ることが出来る売却アイテム
item.serp:subr.name=§g黒のポケ書(160)\n\n§o§7ショップで売ることが出来る売却アイテム
item.serp:subri.name=§e黄のポケ書(640)\n\n§o§7ショップで売ることが出来る売却アイテム
item.serp:subrin.name=§a緑のポケ書(2560)\n\n§o§7ショップで売ることが出来る売却アイテム
item.serp:subring.name=§d桃のポケ書(10240)\n\n§o§7ショップで売ることが出来る売却アイテム
item.serp:mita_stone.name=§dみたまいし\n\n§o§7邪悪な力を引き出すとても危険な石
item.serp:bin.name=§bネレイドの瓶\n\n§o§7ポケモンに使用できるアイテム
item.serp:dnac.name=§gいでんしのくさび\n\n§o§7とある場所に使うとキュレムが現れる。
item.serp:shion.name=§a芽吹きの翔音羽\n\n§o§cとある場所で使うと封印された凶悪なMPLを呼び出すことが出来る
item.serp:poi.name=§cかえんだま\n\n§o§7持ってスニークするとダメージを受ける
item.serp:jirachi_offering.name=§bジラーチの石盤
item.serp:fire_stone.name=§cほのおのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:leaf_stone.name=§aリーフのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:water_stone.name=§bみずのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:thunder_stone.name=§6かみなりのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:moon_stone.name=§gつきのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:dusk_stone.name=§dやみのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:love_sweet.name=ようせいのはね
item.serp:mesame.name=§bめざめいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:kiba.name=キバのかけら
item.serp:fang.name=するどいキバ\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:pot.name=われたポット\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:ice_stone.name=§bこおりのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:ppot.name=§aケッサクのちゃわん\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:kuro.name=§6くろのきせき\n\n§o§7ストライクの進化に使える貴重なアイテム
item.serp:electirizer.name=エレキブースター\n\n§o§7エレブーのポケモンの進化に使える貴重なアイテム
item.serp:magmarizer.name=マグマブースター\n\n§o§7ブーバーのポケモンの進化に使える貴重なアイテム
item.serp:protector.name=プロテクター\n\n§o§7サイドンの進化に使える貴重なアイテム
item.serp:reaper_cloth.name=れいかいのぬの\n\n§o§7サマヨールのポケモンの進化に使える貴重なアイテム
item.serp:sweet_apple.name=§dみついりりんご\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:dragon_scale.name=りゅうのウロコ\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:alora.name=古代の四葉\n\n§o§7ヒスイ地方に関係がある古の四葉。
item.serp:p_block.name=§6ピートブロック\n\n§o§7リングマの進化に使える貴重なアイテム
item.serp:air_stone.name=ブリーズストーン\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:vari_stone.name=ヴァリアントストーン\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:shiny_stone.name=§eひかりのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:ase_stone.name=ナナイロレンズ\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:haki.name=はっきんだま\n\n§o§gギラティナを呼び出せる宝石
item.serp:gin_ingot.name=ベースインゴット\n\n§o§7進化石のベースになるクラフト素材
item.serp:tume.name=するどいツメ\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:hari.name=古代の毒針
item.serp:maco.name=セツナノリング
item.serp:g_armor.name=§cイワイノヨロイ\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:s_armor.name=§dノロイノヨロイ\n\n§o§7一定のポケモンの進化に使える貴重なアイテム
item.serp:gol.name=§eこだいのこうか\n\n§o§716スタック分集めるとアイテムと交換できる
item.serp:kinka.name=§e硬貨のコイン袋\n\n§o§7コレクレーの進化に使えるコイン袋
item.serp:kinkac.name=§a汚れた硬貨のコイン袋\n\n§o§7コレクレーの進化に使えるコイン袋…
item.serp:fossil_root.name=§aねっこのかせき\n\n§o§7孵化装置で復元することが出来る化石。
item.serp:fossil_claw.name=§gツメのかせき\n\n§o§7孵化装置で復元することが出来る化石。
item.serp:cherin.name=§gアドバンス§dチェリー\n\n§o§7上位のアイテムを作れる素材
item.serp:korai.name=§cスカーレットブック【解放:コライドン】
item.serp:mirai.name=§dバイオレットブック【解放:ミライドン】
item.serp:dia.name=§dディアンシーのお供え物【解放:ディアンシー】
item.serp:d_k.name=§e雷の鍵§f
item.serp:balloon.name=§c浮遊ふうせん\n\n§o§7持っているとゆっくり浮遊する
item.serp:balloons.name=§d浮遊ふうせんII\n\n§o§7持っているとドンドン浮遊する
item.serp:balloonp.name=§6浮遊ふうせんIII\n\n§o§7持っていると神速で浮遊する
item.serp:suka.name=§bスピードスカーフ\n\n§o§7ホットバーにあると移動速度が1.4倍になる
item.serp:sukas.name=§cスピードスカーフII\n\n§o§7ホットバーにあると移動速度が2.2倍になる
item.serp:sukap.name=§6スピードスカーフIII\n\n§o§7ホットバーにあると移動速度が???倍になる
item.serp:cond.name=§bすいちゅうのおまもり\n\n§o§7ホットバーにあると水中で溺れない
item.serp:conds.name=§aすいちゅうのおまもりII\n\n§o§7ホットバーにあると水中で溺れない\nさらに暗視効果が付く
item.serp:bboots.name=§aハイジャンプブーツ\n\n§o§7ホットバーにあるとジャンプ力が2倍になる
item.serp:bbootss.name=§bハイジャンプブーツII\n\n§o§7ホットバーにあるとジャンプ力が4倍になる
item.serp:bbootsp.name=§aハイジャンプブーツIII\n\n§o§7ホットバーにあるとジャンプ力が???倍になる
item.serp:hati.name=§cこだわりハチマキ\n\n§o§7ホットバーにあると攻撃力が+3上乗せされる
item.serp:pack.name=§aちゃくちパック\n\n§o§7ホットバーにあると低速落下が付与される
item.serp:kasa.name=§cしゅごのがさ\n\n§o§7ホットバーにあると受けるダメージを半分にする
item.serp:moku_shiny.name=§aキラモクローすこすこぬいぐるみ\n\n§o§7おい？嘘だろ？やめろよ？すこすこしてきたな
item.serp:moku.name=モクローすこすこぬいぐるみ\n\n§o§7オールタイム・モクモクモク
item.serp:pichu_plush.name=§eピチューぬいぐるみ\n\n§o§7ポケモンにあげると仲良し度が上がる
item.serp:clefairy_plush.name=§dピッピぬいぐるみ\n\n§o§7ポケモンにあげると仲良し度が上がる
item.serp:metal_coat.name=メタルコート
item.serp:moomoo_milk.name=モーモーミルク\n\n§o§7ポケモンのHP50回復できる。
item.serp:sun_stone.name=§6たいようのいし\n\n§o§7一定のポケモンの進化に使える貴重なアイテム

Equippables#####################################

equippable.0=なし
equippable.1=クラボのみ
equippable.2=カゴのみ
equippable.3=ナゾのみ
equippable.4=ロメのみ
equippable.5=ヒメリのみ
equippable.6=ラムのみ
equippable.7=マゴのみ
equippable.8=ナナのみ
equippable.9=オレンのみ
equippable.10=シーヤのみ
equippable.11=パイルのみ
equippable.12=ズリのみ
equippable.13=リンドのみ
equippable.14=オボンのみ
equippable.15=マトマのみ
equippable.26=§aぎんいろのこな
equippable.27=§dくろいメガネ
equippable.28=§1りゅうのキバ
equippable.29=§eじしゃく
equippable.30=§dようせいのはね
equippable.31=§dくろおび
equippable.32=§cもくたん
equippable.33=§bするどいクチバシ
equippable.34=§dのろわれたおふだ
equippable.35=§aきせきのたね
equippable.36=§gやわらかいすな
equippable.37=§bとけないこおり
equippable.38=§dどくばり
equippable.39=シルクのスカーフ
equippable.40=§dまがったスプーン
equippable.41=§6かたいいし
equippable.42=§bメタルコート
equippable.43=§bしんぴのしずく
equippable.61=§gおうじゃのしるし
equippable.62=§cきあいのハチマキ
equippable.63=§cたべのこし
equippable.65=
equippable.=

Potions#####################################

item.serp:potion.name=キズぐすり\n\n§o§7ポケモンのHP20回復する。
item.serp:super_potion.name=いいキズぐすり\n\n§o§7ポケモンのHP60回復する。
item.serp:p_up.name=アップグレード\n\n§o§7ポリゴンに使う事で進化できるアイテム。
item.serp:p_aya.name=あやしいパッチ\n\n§o§7ポリゴン2に使う事で進化できるアイテム。
item.serp:hyper_potion.name=すごいキズぐすり\n\n§o§7ポケモンのHP120回復する。
item.serp:max_potion.name=まんたんのくすり\n\n§o§7ポケモンのHPを全て回復する。
item.serp:full_restore.name=かいふくのくすり\n\n§o§7ポケモンのHPを全て回復し、状態異常を治す。
item.serp:full_heal.name=なんでもなおし\n\n§o§7状態異常を治す。
item.serp:fresh_water.name=おいしいみず\n\n§o§7ポケモンのHP30回復する。
item.serp:lemonade.name=ミックスオレ\n\n§o§7ポケモンのHP70回復する。
item.serp:soda_pop.name=サイコソーダ\n\n§o§7ポケモンのHP50回復する。
item.serp:pokepuff_sweet.name=スイートポフレ\n\n§o§7ポケモンにあげるとなつき度が上昇する。
item.serp:pokepuff_mint.name=フレッシュポフレ\n\n§o§7ポケモンにあげるとなつき度が上昇する。
item.serp:pokepuff_citrus.name=サワーポフレ\n\n§o§7ポケモンにあげるとなつき度が上昇する。
item.serp:pokepuff_mocha.name=ビターポフレ\n\n§o§7ポケモンにあげるとなつき度が上昇する。
item.serp:pokepuff_spice.name=スパイシーポフレ\n\n§o§7ポケモンにあげるとなつき度が上昇する。

serp.release_multi_confirm=逃がすポケモンの数:
serp.main.stg=まとめて逃がす
serp.release_multi_done=ポケモンを逃がしました:
serp.release_multi=まとめて逃がす

MT#############################################

item.serp:tm_1.name=むしわざマシン
item.serp:tm_2.name=あくわざマシン
item.serp:tm_3.name=ドラゴンわざマシン
item.serp:tm_4.name=でんきわざマシン
item.serp:tm_5.name=フェアリーわざマシン
item.serp:tm_6.name=かくとうわざマシン
item.serp:tm_7.name=ほのおわざマシン
item.serp:tm_8.name=ひこうわざマシン
item.serp:tm_9.name=ゴーストわざマシン
item.serp:tm_10.name=くさわざマシン
item.serp:tm_11.name=じめんわざマシン
item.serp:tm_12.name=こおりわざマシン
item.serp:tm_13.name=ノーマルわざマシン
item.serp:tm_14.name=どくわざマシン
item.serp:tm_15.name=エスパーわざマシン
item.serp:tm_16.name=いわわざマシン
item.serp:tm_17.name=はがねわざマシン
item.serp:tm_18.name=みずわざマシン
item.serp:tm_19.name=サウンドわざマシン
item.serp:tm_20.name=シャインわざマシン
item.serp:j_a.name=§aむしクラフトジュエル
item.serp:j_b.name=§8あくクラフトジュエル
item.serp:j_c.name=§3ドラゴンクラフトジュエル
item.serp:j_d.name=§eでんきクラフトジュエル
item.serp:j_e.name=§dフェアリークラフトジュエル
item.serp:j_f.name=§4かくとうクラフトジュエル
item.serp:j_g.name=§cほのおクラフトジュエル
item.serp:j_h.name=§bひこうクラフトジュエル
item.serp:j_i.name=§dゴーストクラフトジュエル
item.serp:j_j.name=§aくさクラフトジュエル
item.serp:j_k.name=§6じめんクラフトジュエル
item.serp:j_l.name=§bこおりクラフトジュエル
item.serp:j_m.name=§fノーマルクラフトジュエル
item.serp:j_n.name=§5どくクラフトジュエル
item.serp:j_o.name=§dエスパークラフトジュエル
item.serp:j_p.name=§6いわクラフトジュエル
item.serp:j_q.name=§fはがねクラフトジュエル
item.serp:j_r.name=§bみずクラフトジュエル


serp.mark_list=持っている証
serp.mark_none=このポケモンは証を所持していません
serp.mark_set=この証を設定
serp.mark_equipped_name=付けると表示される名前
serp.mark_currently_equipped=現在付けている証
serp.mark_unset=証を外す

serp.m1=ときどきみるあかし\nレア度:★☆☆☆☆
serp.m2=みたことのないあかし\nレア度:§g★★★★★§r
serp.m3=あかつきのあかし\nレア度:★★☆☆☆
serp.m4=しょうごのあかし\nレア度:★★☆☆☆
serp.m5=たそがれのあかし\nレア度:★★☆☆☆
serp.m6=しょうしのあかし\nレア度:★★☆☆☆
serp.m7=かんそうのあかし\nレア度:★★☆☆☆
serp.m8=どんてんのあかし\nレア度:★★☆☆☆
serp.m9=あめふりのあかし\nレア度:★★☆☆☆
serp.m10=いかずちのあかし\nレア度:★★☆☆☆
serp.m11=こうせつのあかし\nレア度:★★☆☆☆
serp.m12=のうむのあかし\nレア度:★★★☆☆
serp.m13=さじんのあかし\nレア度:★★☆☆☆
serp.m14=かいちょーのあかし\nレア度:★★★☆☆
serp.m15=カリスマのあかし\nレア度:★★★☆☆
serp.m16=きたいのあかし\nレア度:★★★☆☆
serp.m17=きんちょうのあかし\nレア度:★★★☆☆
serp.m18=けんたいのあかし\nレア度:★★★☆☆
serp.m19=げきはつのあかし\nレア度:★★★☆☆
serp.m20=げんきのあかし\nレア度:★★★☆☆
serp.m21=こうかつのあかし\nレア度:★★★☆☆
serp.m22=こうようのあかし\nレア度:★★★☆☆
serp.m23=こわもてのあかし\nレア度:★★★☆☆
serp.m24=じしんのあかし\nレア度:★★★☆☆
serp.m25=じょうねつのあかし\nレア度:★★★☆☆
serp.m26=たこうのあかし\nレア度:★★★☆☆
serp.m27=どうようのあかし\nレア度:★★★☆☆
serp.m28=のうてんのあかし\nレア度:★★★☆☆
serp.m29=びしょうのあかし\nレア度:★★★☆☆
serp.m30=ひそうのあかし\nレア度:★★★☆☆
serp.m31=ふしんのあかし\nレア度:★★★☆☆
serp.m32=ふじゅんのあかし\nレア度:★★★☆☆
serp.m33=ふちょーのあかし\nレア度:★★★☆☆
serp.m34=ふんぬっのあかし\nレア度:★★★☆☆
serp.m35=こはくのあかし\nレア度:★★★☆☆
serp.m36=ほんのうのあかし\nレア度:★★★☆☆
serp.m37=あざとさのあかし\nレア度:★★★☆☆
serp.m38=ゆだんのあかし\nレア度:★★★☆☆
serp.m39=りせいのあかし\nレア度:★★★☆☆
serp.m40=れいせいのあかし\nレア度:★★★☆☆
serp.m41=わんぱくのあかし\nレア度:★★★☆☆
serp.m42=びしょくかのあかし\nレア度:★☆☆☆☆
serp.m43=ものひろいのあかし\nレア度:★☆☆☆☆
serp.m44=なかよしリボン\nレア度:★☆☆☆☆
serp.m45=ハスノソラのあかし\nレア度:★★★★☆
serp.m46=オヤブンのあかし\nレア度:★☆☆☆☆
serp.m47=あいぼうのあかし\nレア度:★★★☆☆
serp.m48=ののあのあかし\nレア度:★★★☆☆
serp.m49=ゆきのあかし\nレア度:★★★☆☆
serp.m50=ポピコのあかし\nレア度:★★★☆☆
serp.m51=ホウエンチャンプリボン\nレア度:★★☆☆☆
serp.m52=ポケリエリボン\nレア度:★★★★★
serp.m53=ふかでうまれたあかし\nレア度:★☆☆☆☆


serp.m_1=ひとになれてる
serp.m_2=ひとをしらない
serp.m_3=はやくにめざめた
serp.m_4=はらぺコの
serp.m_5=そろそろねむい
serp.m_6=おねむな
serp.m_7=のどカラカラの
serp.m_8=くもをみつめる
serp.m_9=あめにむせぶ
serp.m_10=かみなりにさわぐ
serp.m_11=ゆきにころがる
serp.m_12=きりにとまどう
serp.m_13=すなにまみれる
serp.m_14=ごきげんな
serp.m_15=オーラをかんじる
serp.m_16=ワクワクしてる
serp.m_17=ドキドキしてる
serp.m_18=やるきゼロの
serp.m_19=ふきげんな
serp.m_20=げんきいっぱいの
serp.m_21=スキをねらう
serp.m_22=やるきまんまんの
serp.m_23=いかつい
serp.m_24=ふんぞりかえった
serp.m_25=アグレッシブな
serp.m_26=しあわせそうな
serp.m_27=あわてんぼうの
serp.m_28=なにもかんがえてない
serp.m_29=ニコニコわらう
serp.m_30=メソメソなく
serp.m_31=じしんのない
serp.m_32=きどっている
serp.m_33=どこかくたびれた
serp.m_34=プンプンおこる
serp.m_35=ステラソラな
serp.m_36=あれくるう
serp.m_37=やさしげな
serp.m_38=ボーっとしてる
serp.m_39=ちてきな
serp.m_40=クールな
serp.m_41=あばれんぼうの
serp.m_42=そよかぜをそえる
serp.m_43=トレジャーハンター
serp.m_44=しんゆうの
serp.m_45=スクールアイドルの
serp.m_46=オヤブンだった
serp.m_47=たよれるあいぼうの
serp.m_48=まぼろしをおう
serp.m_49=ゆきにたたずむ
serp.m_50=はなびらまう
serp.m_51=ホウエンチャンピオン
serp.m_52=さいこうのパートナーの
serp.m_53=おとぎばなしの

serp.mark_equipped_prefix=現在付けている称号:






Actions#####################################

 action.interact.bet=ベット
 action.interact.store=セーブ
 action.interact.activate=アクティブ

Spawn Eggs##################################

entity.pokemon:p0.name=なし
item.spawn_egg.entity.serp:bike.name=バイク
item.serp:pokebike.name=バイク
item.serp:poke_bike.name=バイク
item.spawn_egg.entity.serp:poke_stop.name=Poke Stop
item.spawn_egg.entity.serp:joy.name=Nurse Joy
item.spawn_egg.entity.serp:jenny.name=Officer Jenny
item.spawn_egg.entity.serp:store.name=Pokestore
item.serp:rotomarket.name=ロトムマーケット\n\n§o§7置くことでどこでもショップを開ける
item.serp:healing_machine.name=回復装置\n\n§o§7ポケモン用の回復装置を置くことが出来る
item.serp:pc_box.name=ポケモンPC\n\n§o§7ポケモンの管理を出来るパソコン
item.serp:mini_lab.name=復元・孵化装置\n\n§o§7孵化や復元が出来る機械
item.serp:trade_machine.name=交換装置
item.serp:communicator.name=電話
item.serp:slot_machine.name=スロットマシン\n\n§o§7スロットマシンを置くことが出来る
entity.pa:pw.name=エコロシア
combat.choose_target=攻撃する相手を選んでください
serp.single_battle_request=シングルバトル
serp.double_battle_request=ダブルバトル
serp.pokeradar=このポケモンの色違い確率をあげました:

conditions###################################

condition.0=§z
condition.1=
condition.2=
condition.3=
condition.4=
condition.5=
condition.6=
condition.7=
condition.8=

battle#######################################

mechanic.0=T-A-S
mechanic.1=メガシンカ
mechanic.2=ダイマックス
combat.volt_switch_select=交代先を選んでください

attack.class_status=変化技
attack.base_priority=技の優先度: 
attack.base_power=威力: 
attack.base_accuracy=命中率: 
attack.effect=主な追加効果: 
attack.target1=自分が対象
attack.target0=§r全員が対象
attack.target2=§r相手単体が対象
attack.target3=§r自分以外の味方全員が対象
attack.target4=§r自分も含む味方全体が対象
attack.target5=§rランダムな相手単体が対象
attack.target6=§r相手全体が対象
attack.target7=§r自分以外が対象

attack.0=--
attack.1= れんぞくぎり
attack.2= とどめばり
attack.3= とんぼがえり
attack.4= であいがしら
attack.5= とびつく
attack.6= とびかかる
attack.7= きゅうけつ
attack.8= よってたかる
attack.9= メガホーン
attack.10= ジェットスピア
attack.11= むしのていこう
attack.12= ぎんいろのかぜ
attack.13= バグノイズ
attack.14= ぼうぎょしせい
attack.15= いとをはく
attack.16= ちょうのまい
attack.17= かくらんひこう
attack.18= §d翔音§fセレナーデ
attack.21= ダメおし
attack.22= はたきおとす
attack.23= つじぎり
attack.24= かみつく
attack.25= かみくだく
attack.26= ぶちこわす
attack.27= ないしょばなし
attack.28= じゃあくなキバ
attack.29= ふいうち
attack.30= しっぺがえし
attack.31= バークアウト
attack.32= あくのはどう
attack.33= ナイトバースト
attack.34= つめとぎ
attack.35= おだてる
attack.36= ダークロアー
attack.37= ライフドレイン
attack.38= わるだくみ
attack.39= グリムハウル
attack.40= ナイトアセット
attack.41= ワイドブレイカー
attack.42= ドラゴンクロー
attack.43= げきりん
attack.44= ドラゴンダイブ
attack.45= ダイナソード
attack.46= 覇者の爪痕
attack.47= プルスウルトラ
attack.48= スケイルショット
attack.51= たつまき
attack.52= りゅうのいぶき
attack.53= りゅうせいぐん
attack.54= りゅうのはどう
attack.55= りゅうのいかり
attack.56= りゅうのまい
attack.57= 穿星波
attack.58= リューズバスター
attack.59= §9エルダーバースト§r
attack.61= かみなりのキバ
attack.62= かみなりパンチ
attack.63= サンダーダイブ
attack.64= スパーク
attack.65= アクセルボルト
attack.66= エレキスピン
attack.67= パルスブレイク
attack.68= カッターボルト
attack.69= §eボルテッカー§r
attack.70= オーバードライブ
attack.71= でんきショック
attack.72= 10まんボルト
attack.73= かみなり
attack.74= エレキネット
attack.75= ほうでん
attack.76= パラボラチャージ
attack.77= マッハボルト
attack.78= ルクシオンエア
attack.79= ルクスノヴァ
attack.80= ボルトチェンジ
attack.81= じゃれつく
attack.82= ソウルクラッシュ
attack.83= ピアーネイル
attack.84= メロメロパンチ
attack.85= パワーハグ
attack.86= フェアリーゲイン
attack.87= あまえる
attack.88= うさぎとび
attack.91= ドレインキッス
attack.92= ようせいのかぜ
attack.93= ムーンフォース
attack.94= てんしのキッス
attack.95= つぶらなひとみ
attack.96= みわくのボイス
attack.97= あやかしのキリ
attack.98= トワイライト
attack.99= ミストバースト
attack.101= からてチョップ
attack.102= グロウパンチ
attack.103= インファイト
attack.104= クロスチョップ
attack.105= かわらわり
attack.106= アームハンマー
attack.107= マッハパンチ
attack.108= ボディプレス
attack.109= きしかいせい
attack.111= しんくうは
attack.112= はどうだん
attack.113= きあいだま
attack.114= ビルドアップ
attack.115= しゅうきほう
attack.116=ファイナルラウンド
attack.117= オーラファイト
attack.118= 白の衝撃
attack.121= ようびのまい
attack.122= ほのおのパンチ
attack.123= フレアドライブ
attack.124= ほのおのキバ
attack.125= ブレイズキック
attack.126= せんこうはなび
attack.127= ねたみのいかり
attack.128= かじばのいちげき
attack.131= ひのこ
attack.132= かえんほうしゃ
attack.133= だいもんじ
attack.134= おにび
attack.135= はじけるほのお
attack.136= §cきたかぜたいよう§r
attack.137= ねっぷう
attack.138= かさいせんぷう
attack.139= ラピッドフレア
attack.140= オーバーヒート
attack.141= つつく
attack.142= アクロバット
attack.143= つばさでうつ
attack.144= ブレイブバード
attack.145= ドリルくちばし
attack.146= かっくう
attack.147= ジェットシュート
attack.148= きゅうこうか
attack.149= メテオウィング
attack.150= むらくもばらい
attack.151= かぜおこし
attack.152= エアーカッター
attack.153= かみかぜ
attack.154= かまいたち
attack.155= ジェットきりゅう
attack.156= しはいのかぜ
attack.157= かみわたし
attack.158= ターボストーム
attack.159= §bはねやすめ§r
attack.160= おいかぜ
attack.161= したでなめる
attack.162= かげうち
attack.163= シャドークロー
attack.164= シャドーパンチ
attack.165= おどろかす
attack.166= いのちとり
attack.167= あんやのつばさ
attack.168= §d朧一閃§r
attack.169= ソウルシェイプ
attack.171= あやしいかぜ
attack.172= ひゃっきやこう
attack.173= シャドーボール
attack.174= あやしいひかり
attack.175= たたりめ
attack.176= のりうつる
attack.177= カオストリック
attack.178= カースブラスト
attack.179= §d不倶戴天§r
attack.180= テラーバインド
attack.181= このは
attack.182= はっぱカッター
attack.183= リーフブレード
attack.184= ブルームエッジ
attack.185= ウッドハンマー
attack.186= くるいざき
attack.187= グロウブレード
attack.188= くさわけ
attack.189= タネマシンガン
attack.191= すいとる
attack.192= メガドレイン
attack.193= リーフストーム
attack.194= エナジーボール
attack.195= コットンパワー
attack.196= ねむりごな
attack.197= マジカルリーフ
attack.198= いばらがため
attack.199= ウィンドミル
attack.200= §a弓張月§r
attack.201= じならし
attack.202= 10まんばりき
attack.203= じしん
attack.204= ドリルライナー
attack.205= ソイルシュート
attack.206= §6獣王の牙§r
attack.207= サンドレイク
attack.208= §6韋駄天§f
attack.211= どろかけ
attack.212= マッドショット
attack.213= どろばくだん
attack.214= すなかけ
attack.215= ねっさのだいち
attack.216= だいちのちから
attack.217= アースライザー
attack.218= ガイアキューブ
attack.219= マグナライズ
attack.221= こおりのつぶて
attack.222= こおりのキバ
attack.223= れいとうパンチ
attack.224= つららおとし
attack.225= せいひょう
attack.226= ひややかパンチ
attack.227= スリートスピア
attack.228= ゆきなだれ
attack.229= トリプルアクセル
attack.231= こなゆき
attack.232= こごえるかぜ
attack.233= れいとうビーム
attack.234= オーロラビーム
attack.235= ふぶき
attack.236= ブリザード
attack.237= ヘイルストーム
attack.238= アイシイ
attack.239= くろいきり
attack.241= たいあたり
attack.242= ひっかく
attack.243= しんそく
attack.244= ほしがる
attack.245= ロケットずつき
attack.246= みねうち
attack.247= いあいぎり
attack.248= すてみタックル
attack.249= スピンテール
attack.250= メガトンパンチ
attack.251= だいばくはつ
attack.252= スピードスター
attack.253= はかいこうせん
attack.254= きりふだ
attack.255= ハイパーボイス
attack.256= エコーボイス
attack.257= しっぽをふる
attack.258= なきごえ
attack.259= つるぎのまい
attack.260=ドラマチックな登場
attack.261= どくどくのキバ
attack.262= どくづき
attack.263= ダストシュート
attack.264= ポイズンテール
attack.265= ポイズンリーフ
attack.266= クロスポイズン
attack.267= ブラッドネイル
attack.271= アシッドボム
attack.272= べノムショック
attack.273= ヘドロばくだん
attack.274= どくどく
attack.275= ふしょくのきり
attack.276= スモッグ
attack.277= バッドポイズン
attack.278= カオスウェーブ
attack.281= サイコカッター
attack.282= しねんのずつき
attack.283= ハートスタンプ
attack.284= サイコファング
attack.285= ふゆのひざし
attack.286= バリアブラスト
attack.287= オルタナティブ
attack.291= ねんりき
attack.292= サイコキネシス
attack.293= さいみんじゅつ
attack.294= サイコショック
attack.295= せんせいじゅつ
attack.296= §d御神楽§r
attack.297= §dテレポート§r
attack.298= ドわすれ
attack.299= めいそう
attack.300= §dアルカナフール§r
attack.301= いわおとし
attack.302= がんせきふうじ
attack.303= ストーンエッジ
attack.304= もろはのずつき
attack.305= いわなだれ
attack.306= ついげき
attack.307= グランボールダ
attack.308= §6山麓崩壊§r
attack.309= ロックブラスト
attack.311= げんしのちから
attack.312= パワージェム
attack.313= メテオビーム
attack.314= ロックカット
attack.315= ジェムレーザー
attack.316= こだいのいぶき
attack.317= グラベルブレス
attack.318= ステルスロック
attack.321= メタルクロー
attack.322= スマートホーン
attack.323= アイアンテール
attack.324= バレットパンチ
attack.325= アイアンヘッド
attack.326= はがねのつばさ
attack.327= コメットパンチ
attack.328= ざんてつけん
attack.329= デスラティス
attack.330= ランチャーアーム
attack.331= ミラーショット
attack.332= ラスターカノン
attack.333= フルバースト
attack.334= ジオ・バスター
attack.335= じりょくせん
attack.336= スターダスト
attack.337= てっぺき
attack.338= ラディアカノン
attack.341= アクアジェット
attack.342= たきのぼり
attack.343= アクアテール
attack.344= アクアブレイク
attack.345= マリンドロップ
attack.346= ウェーブタックル
attack.347= デプスレーン
attack.348= ディーナスバイト
attack.349= クイックターン
attack.351= あわ
attack.352= みずのはどう
attack.353= ハイドロポンプ
attack.354= アクアボルト
attack.355= なみのり
attack.356= アクアバリア
attack.357= アクアスワール
attack.358= ゆうだち
attack.359= §bみずしゅりけん§r
attack.361= §aラルゴ§f
attack.362= §aランボア§f
attack.363= §aヘビー・バス§f
attack.364= §aドルケストラ§f
attack.365= §aヴィヴァーチェ§f
attack.366= §aデスアルト§f
attack.367= §aシーケンス§f
attack.371= §aアンダンテ§f
attack.372= §aフェルマータ§f
attack.373= §aグラツィオーソ§f
attack.374= §aミキシング§f
attack.375= §aシンフォニア§f
attack.376= §aアブソリュート§r
attack.377= §a愛スクリ〜ム!§r
attack.381= §gグロウバイト§f
attack.382= §gせいなるや§f
attack.383= §gバニシング§f
attack.384= §gジャッジメント§f
attack.385= §gブロッサムライト§f
attack.386= §gグローイクリプス§f
attack.387= §gひかりのやいば§f
attack.388= §gストロボエッジ§f
attack.389= §gゼニスオブソード§f
attack.391= §gスポットライト§f
attack.392= §gサーチライト§f
attack.393= §gシャイニング§f
attack.394= §gフレア§f
attack.395= §g稲光§f
attack.396= §gはじける閃光§f
attack.397= §gせつげつこう§f
attack.398= §g眩しい暗闇§f
attack.399= §g終光§f
attack.401= はたく
attack.402= たたきつける
attack.403= つのでつく
attack.404= とっしん
attack.405= でんこうせっか
attack.406= きりさく
attack.407= ブレイククロー
attack.408= うちとる
attack.409= いあい
attack.411= ロックオン
attack.412= こわいかお
attack.413= かくばる
attack.414= きあいだめ
attack.415= いやなおと
attack.416= めまわし
attack.417= くすぐる
attack.418= トライアタック
attack.419=§dゴートゥーヘル§r
attack.431= §dはめつのひかり§r
attack.432= §dめざめるパワー§r
attack.441= §dマーズエネルギー§r
attack.451= §6スタアラッシュ§r
attack.452= §aしぐれうち§f
attack.453= §dえいどくむ§r
attack.454= §dソウルピアス§f
attack.455= §dイオンハート§r
attack.461= れんぞくパンチ
attack.471= クリアカード
attack.472= テレキネシス
attack.473= イカサマ
attack.474= §dトリックルーム§r
attack.475= §dリフレクター§r
attack.476= §dひかりのかべ§r
attack.477= バトンタッチ
attack.478= きりばらい
attack.479= ゆびをふる
attack.480= §cインフェルノ§r
attack.481= §dつみほろぼし§r
attack.482= §dナナイロレーザー§r
attack.483= §bメイルストローム§r
attack.484= §aイルミンスール§r
attack.485= ちょうはつ
attack.486= グラスフィールド
attack.487= エレキフィールド
attack.488= サイコフィールド
attack.489= ミストフィールド
attack.490= メロディフィールド
attack.491= §aこだまのさけび§r
attack.492= アンコール
attack.493= うつせみ
attack.494= §dエリミネイト§r
attack.495= §gリプループラグ§r
attack.496= §bハリケーン§r
attack.497= じこさいせい
attack.498= §aあさなぎ§r
attack.499= §cやけ§aのはら§r
attack.500= §d有刺鉄線§r
attack.501= §bブルージェット§r
attack.502= §b黒潮§r
attack.503= ウェザーボール
attack.504= だいちのはどう
attack.505= チャージ






attack.1000=アイテムを使用した
attack.1001=このターンは行動できない！
attack.1002=自分を攻撃した
attack.1003=攻撃は失敗した
attack.1004=怯んだ！
attack.2001=ダイワーム
attack.2002=ダイアーク
attack.2003=ダイドラグーン
attack.2004=ダイサンダー
attack.2005=ダイフェアリー
attack.2006=ダイナックル
attack.2007=ダイバーン
attack.2008=ダイジェット
attack.2009=ダイホロウ
attack.2010=ダイソウゲン
attack.2011=ダイアース
attack.2012=ダイアイス
attack.2013=ダイストライク
attack.2014=ダイアシッド
attack.2015=ダイサイコ
attack.2016=ダイロック
attack.2017=ダイスチル
attack.2018=ダイストリーム
attack.2019= まもる

serp.tms=使えるわざマシン: 
serp.wildlevel=野生でのレベル:
serp.evolutions=§r
serp.evoT.1=§r
serp.evoT.2=§r
serp.evoT.3=§r
serp.evoT.4=§r
serp.evoQ.0=§r
serp.evoQ.1=§r
serp.evoQ.2=§r
serp.evoQ.3=§r
serp.evoQ.4=§r
serp.evoQ.5=§r
serp.evoQ.6=§r
serp.this_turn=ターン



ability.0=§r
ability.1=アンノウンタイプ\n(自身への タイプ相性 が無くなる)
ability.2=あめふらし\n(とうじょう したときに 5ターンのあいだ てんきを あめに する)
ability.3=かそく\n[すばやく なっていく]
ability.4=カブトアーマー\n[わざを きゅうしょに うけない]
ability.5=がんじょう\n(HPが 満タンのとき 技を 受けても 一撃で 倒されることが ない)
ability.6=じゅうなん\n[まひに ならない]
ability.7=うみうつし\n[こうげきと とくこう しゅぞくちが たかいほうと おなじになる]
ability.8=せいでんき\n[さわった あいてを たまにしびれさせる]
ability.9=ちくでん\n[でんきを うけない]
ability.10=ちょすい\n[みずを うけない]
ability.11=ふみん\n[ねむらない]
ability.12=§r
ability.13=？
ability.14=もらいび\n[調べて]
ability.15=?????\n(ちかくに いるだけで とてつもない いあつを かんじる・・・)
ability.16=いかく\n(登場 したとき 威嚇して 相手を 委縮させ 相手の 攻撃を 下げて しまう)
ability.17=きずつけボディ\n[さわった あいてを キズつける]
ability.18=§r
ability.19=ふゆう\n(じめんから うくことによって じめんタイプの わざを うけない)
ability.20=ゲノムコピー\n(全ての通常わざマシンを使うことが出来る)
ability.21=スケッチ\n(一部専用を除く全てのわざマシンを使うことが出来る)
ability.22=？
ability.23=すいすい\n[あめのとき すばやさが はやくなる]
ability.24=ようりょくそ\n[ひでりのとき すばやさが はやくなる]
ability.25=§r
ability.26=？
ability.27=？
ability.28=？
ability.29=？
ability.30=あめうけざら\n[あめのとき すこしずつ かいふく]
ability.31=すなおこし\n(とうじょう したときに 5ターンのあいだ てんきを すなあらしに する)
ability.32=プレッシャー\n[あいての PPが へりやすい]
ability.33=あついしぼう\n[ほのお こおりに つよい]
ability.34=ほのおのからだ\n[さわった あいてを たまに やけどにさせる]
ability.35=フラワーギフト\n(フォルムチェンジできるようになり、HP以外のステータスが1.5倍になる)
ability.36=なまけ\n[れんぞくで こうどう できない]
ability.37=？
ability.38=？
ability.39=こんじょう\n(やけどのとき こうげきが あがる)
ability.40=ふしぎなウロコ\n[じょうたい いじょうのとき ぼうぎょがあがる]
ability.41=しんりょく\n[ピンチに くさのいりょくが あがる]
ability.42=もうか\n[ピンチに ほのおのいりょくが あがる]
ability.43=げきりゅう\n[ピンチに みずのいりょくが あがる]
ability.44=むしのしらせ\n[ピンチに むしのいりょくが あがる]
ability.45=はんどうむこう\n(わざの はんどうダメージ をうけない)
ability.46=ひでり\n(とうじょう したときに 5ターンのあいだ てんきを ひでりに する)
ability.51=ふくがん\n[わざが めいちゅう しやすい]
ability.53=テクニシャン\n[いりょくがひくい わざのいりょくが すこしあがる]
ability.54=ふしょく\n[はがね や どく も どくにできる]
ability.56=てんのめぐみ\n[わざのついかこうか がでやすい]
ability.57=ゆきふらし\n(とうじょう したときに 5ターンのあいだ てんきを ゆきに する)
ability.58=？
ability.59=ゆきかき\n[ゆきのとき すばやくなる]
ability.60=すなかき\n[すなあらしのとき すばやくなる]
ability.62=フェアリースキン\n[ノーマルのわざが こおりになる]
ability.63=はやあし\n[いじょうのとき すばやさがあがる]
ability.64=マルチスケイル\n[HPまんたんのとき うけるダメージが へる]
ability.65=あまのじゃく\n(能力の 変化が 逆転して 上がるときに 下がり 下がるときに 上がる)
ability.66=ちからずく\n[わざのいりょくがあがるが ついかこうかが きえる]
ability.67=クリアボディ\n[のうりょくが さがらない]
ability.68=てきおうりょく\n[じぶんと おなじタイプの いりょくが あがる]
ability.69=ノーガード\n[おなじに わざがあたる]
ability.70=かたいつめ\n[せっしょくする わざの いりょくがあがる]
ability.71=いたずらごころ\n[へんかわざを さきにつかえる]
ability.72=レゾナンス\n(サウンドタイプの技の威力が1.2倍になる)
ability.73=きょっこう\n(シャインタイプの技の威力が1.2倍になる)
ability.74=きょううん\n[きゅうしょに あたりやすい]
ability.75=かたやぶり\n[とくせい のこうかを むしする]
ability.76=トレース\n[あいてと おなじ とくせいになる]
ability.77=ハードロック\n[おおきい うけるダメージ がへる]
ability.78=スナイパー\n[きゅうしょが さらに きゅうしょにあたる]
ability.79=はりきり\n[こうげきが たかいが はずれるかも]
ability.80=フリーズスキン\n[ノーマルのわざが こおりになる]
ability.81=エレキスキン\n[ノーマルのわざが でんきになる]
ability.82=ドラゴンスキン\n[ノーマルのわざが ドラゴンになる]
ability.83=サイコスキン\n[ノーマルのわざが エスパーになる]
ability.84=はやてのつばさ\n[ひこうのわざが はやくなる]
ability.85=はっこう\n[ポケモンが ひかりやすくなる]
ability.86=きれあじ\n[きるわざの いりょくが たかくかる]
ability.87=がんじょうあご\n[かむわざの いりょくが たかくかる]
ability.88=メガランチャー\n[はどうわざの いりょくが たかくかる]
ability.89=てつのこぶし\n[こぶしの わざの いりょくが たかくかる]
ability.90=せいしんりょく\n[ひるまない]
ability.91=アルコバレーノ\n[じょうたい いじょうに ならない]
ability.92=するどいめ\n[するどすぎ]
ability.93=すなのちから\n[すなあらしのとき いちぶの わざがつよくなる]
ability.94=そうしょく\n[くさを うけない]
ability.95=ムラっけ\n[まいターン のうりょく1つが 3だんかいあがり のうりょく1つが さがる]
ability.96=サンパワー\n[ひでりのとき とくこうがたかくなるが ダメージをうける]
ability.97=りんぷん\n[わざの ついかこうかを うけない]
ability.98=まけんき\n[のうりょくがさがると こうげきが あがる]
ability.99=かちき\n[のうりょくがさがると とくこうが あがる]
ability.100=アイスブレイク\n[ゆきのとき ちからが あがるが ダメージをうける]
ability.101=むしよけ\n[むしを よける]
ability.102=じきゅうりょく\n[じきゅうりーよが たかい]
ability.103=くだけるよろい\n[ダメージをうけると やわらかくなり はやくなる]
ability.104=ゆうばく\n[ひんしになると あいてをうらむの]
ability.105=のろわれボディ\n[そしてのろうでしょう このからだは]
ability.106=かがくへんかガス\n[ばのぜんいんの とくせいを むこうか]
ability.107=さいせいりょく\n[ひっこめると かいふくする]
ability.108=びんじょう\n[わほー]
ability.109=ぎゃくじょう\n[HPがはんぶん になると いらついて おこ]
ability.110=おみとおし\n[あいての とくせいが みるみるみるみる]
ability.111=ききかいひ\n[兄さん…アカーン！]
ability.112=じしんかじょう\n[あいてを たおすたびに こうげきがあがる]
ability.113=あふれるちしき\n[あいてを たおすたびに とくこうがあがる]
ability.114=ぽかぽかオーラ\n[ポケモンを かなり ほかくしやすくなり ウルトラボールの つかまりにくくなる こうかが なくなる]
ability.115=スキルリンク\n[いっぱい あてれるの]
ability.116=グラスメイカー\n[フィールドをグラスフィールドにする]
ability.117=エレキメイカー\n[フィールドをエレキフィールドにする]
ability.118=サイコメイカー\n[フィールドをサイコフィールドにする]
ability.119=ミストメイカー\n[フィールドをミストフィールドにする]
ability.120=メロディメイカー\n[フィールドをメロディフィールドにする]
ability.121=かげふみ\n[しばくぞお前…そこはアカン言うてる 良かったこの距離で！ ﾝﾊｱｱｱｱｱwww]
ability.122=きけんよち\n[あいての おぼえている わざ2つが わかる]
ability.123=すりぬけ\n[ちょっと待ってwww聖園ミカ(水着)がすり抜けたwwwいやシロコくなー！www・・・のやつやな]
ability.124=ナーバスレイジ\n[ちょうはつ や アンコール のときに こうげきがあがる]
ability.125=マジックミラー\n[変化技を跳ね返す]
ability.126=ソニックガード\n[はやいやつをふせぐ]
ability.127=ファーコート\n[ぶつりをあとは調べて]
ability.128=こおりのりんぷん\n[とくしゅはやめちくり]
ability.129=とうそうしん\n[ゆでだこ]
ability.131=ふしょくのトゲ\n[ダメージを うけると あいてを どくにする]
ability.132=たんじゅん\n[たんじゅんな こ♡]
ability.133=ふんど\n[HPが へると ふんどする]
ability.134=えいきゅうきかん\n[毎ターン、自身は【エナジースタック】を1つ獲得する]
ability.135=レールガン\n[でんきわざを使う時、自身の【エナジースタック】を全て消費し、消費した数が多いほど威力が上がる]
ability.136=エナジーエンジン\n[自身の【エナジースタック】が2つ事にすばやさが上昇、3つでぼうぎょ と とくぼうが あがる]
ability.137=エナジーソウル\n[自身の【エナジースタック】が多いほど、自身のこうげき・とくこうがあがる\n【エナジースタック】を消費すると上がっていた分だけさがる]



attack.parh=この確率で麻痺にすることが出来る。
attack.brnh=この確率で火傷にすることが出来る。
attack.psnh=この確率で毒にすることが出来る。
attack.bpsnh=この確率で毒にすることが出来る。
attack.frzh=この確率で氷にすることが出来る。
attack.confh=この確率で混乱にすることが出来る。

entity.pokemon:p0.name=なし




info.1=体から 発する 甘い香りで まわりを 魅了する。 日光に 当たると 香りは さらに強まる。
info.4=生まれたときから しっぽに 炎が ともっている。 炎が 消えたとき その 命は 終わって しまう。
info.7=繊細な 泡で 体を 包み 肌を 守る。のんきに 見せかけて 抜け目なく 周囲を うかがう。
info.49=ハムスターのような容姿だが、耳はそれに比べて長い。体色は鮮やかな黄色で、背中には茶色の縞模様が2本あり、耳は円錐のような形状で先端が黒くなっており、黒色と黄色の境目は斜めになっている。頬は目を引く円形の赤い丸ほっぺになっている。稲妻型の尻尾も特徴的で、その根本は茶色い。雌雄は、♀のみ尻尾の先が2つに分かれてハート型の模様がついていることで判別できる。前足は5本指で、肩から手まで太さは同じ。後脚は3本指で、薄い板状。色違いの個体は体色が少し濃く、オレンジ色である。頬の赤い部分には電気を溜め込む器官「電気袋」が備わっており、溜めた電気を思いっきり放出すると、雷に匹敵する。警戒する際は、電気袋から放電する。電気袋に触れるとパチパチと痺れる。ほっぺの電気袋がよく伸びて柔らかい個体ほど、強力な電気を作り出せる。睡眠中に電気袋で発電を行っており、寝不足だと電気が弱くなる。同族同士尻尾をくっつけて電気を流しあうことで挨拶し、弱った仲間に電気を分け与えたり、硬いきのみを電撃で焼いて柔らかくして食べたり、初めて見るものに電撃を当てたり、ほっぺから電気を放電して敵を威嚇したりと、ピカチュウにとって電気は、元気の源でも、道具・武器でもある。逆に放電しないでいるとストレスが溜まる。怒ったり、寝ぼけたりして放電してしまうことがある。尻尾を立てることで周囲の気配を察知する能力があり、それ故に尻尾を掴むと噛みつかれる。たまに尻尾で周囲の様子を探っている時に、尻尾に雷が落ちてくる。人気のない森を生息地としてきのみを食し、群れで生活をしている。ピカチュウが何匹も集まると猛烈な電気がその一帯に溜まり、落雷を誘導してしまうため、ピカチュウの群れが暮らす森は落雷が多く、非常に危険。

Pokedex#####################################


weather.0=天候は晴れだ
weather.1=日差しが 強い！
weather.2=雨が 降っている…
weather.3=砂嵐が 吹き荒れている…
weather.4=ゆきが 降っている…

attack.318.set=岩が相手の足元に散らばった！
attack.318.dmg=ステルスロックのダメージを受けた！
attack.318.my_field=自分の場はステルスロック状態だ。
attack.318.opp_field=相手の場はステルスロック状態だ。
attack.495.set=痺れる罠が相手の足元に置かれた！
attack.495.dmg=リプループラグのダメージを受けた！

serp.increases=上昇するステータス:
serp.decreases=下降するステータス:
serp.naturedex=性格図鑑
serp.captured_pokemon=捕まえたポケモンの数:
serp.attackdex=わざ図鑑
store.body_sell=売りたいアイテムを選んでください
serp.attacks=わざ
serp.attack_change=わざを おぼえそうだ:
serp.confirm=はい
serp.cancel=いいえ
serp.can_learn=が わざを おぼえそうだ！
serp.back=戻れ！
serp.cant_learn=わざを おぼえられない！
serp.return=戻れ 
serp.choose_you=行ってこい！
serp.players=トレーナー
serp.combat_request=バトルリクエスト
serp.send_money=ポケリエPayPay
serp.how_many_money=何円プレゼントする？
serp.did_you_sent=送った
serp.did_you_received=受け取った
serp.wants_fight=ポケモン勝負しましょう！
serp.fight_accepted=勝負の始まりだ
serp.fight_refused=断られました；；
serp.closer=プレイヤーにもっと近づいて
serp.cant_interact_with_yourself=自分選んで何するんだFラン
serp.healthy=§aげんき§r
serp.defeated=§cひんし§r
serp.swipped=移動させました
ball.catch=捕まえた！
ball.free=捕まらなかった！
ball.pc=PCへ送られた
serp.team=スロットを選択
serp.pokemonbody=どうする？
serp.pokevial=クイックヒール
serp.reload_pokevial=バッテリー切れのため回復できません
serp.swipe=スロット移動
serp.swipebody=変えたいスロットを選択をしてください
serp.sb=ポケモンを出す/戻す
serp.info=記載無し
serp.remove_item=アイテムを戻す
serp.to_stg=PCへ送る
serp.nickname=ニックネーム
serp.new_nickname=どんなきっしょい名前にする？
serp.use_pc=PC
main.stg=PC menu
serp.stg_body=PCです
serp.change_box.body=どうする？
serp.save_pokemon=回復しとけ
serp.to_team=手持ちにいれる
serp.last_pokemon=最後のポケモン送るな特性かたやぶりか、ボケが学べや。
serp.welcome_back=手持ちにいれる
serp.goodbye_stg=さっさと野生に帰れ
serp.full_team=手持ちがいっぱいだぞ
serp.full_pc=PC満タンとかあるの！？
serp.release=逃がす
serp.stg_release_body=本当に…？
serp.release_confirm=もちろん！こんなの要らない！
serp.release_decline=いや待てよ…
serp.change_box=チェンジボックス
serp.trade_request=トレードメニュー
serp.choose_trader=誰と交換する？
serp.choose_traded=どのポケモンを？
serp.will_trade=このポケモンをあげる
serp.fix_trade=セーブ中
serp.empty_slot=何も無いよ
serp.mt_body=技を覚えるようだ
serp.no_slot_selected=スロットを選択してください
serp.choose_another=このポケモンはバトル中なのです
serp.pokemenu=ポケメニュー
serp.pet=なでなで
mount.1=肩に乗せれるポケモンです
mount.2=§r
mount.3=ライドが出来るポケモンです
serp:mount=アクション: 
serp.battle_b=バトル！
serp.battle=バトルメニュー
serp.close_menu=クローズメニュー
serp.trainer_card=トレーナーカード
serp.trainer=§0§l トレーナー: §r
serp.id=§0§l N.° ID: §r
serp.money=§0§l ポケドル: §r
serp.height=§r
serp.weight=§r
serp.exp=経験値: §r
serp.hp=HP: §r
serp.level=Lv:§r 
serp.dynamaxl=§c覚醒 Lv.: §r 
serp.gigamaxf=キョダイマックス : §r 
serp.gigamax.0=なし §r 
serp.gigamax.1=ある §r 
serp.happiness=仲良し度: §r
serp.nature=個体値: §r
serp.ability=アビリティ: §r
serp.item=持ち物: §r
serp.stats=ステータス: §r
serp.atk=攻撃. §r
serp.atks=特攻. §r
serp.def=防御. §r
serp.defs=特防. §r
serp.spd=素早さ. §r
serp.mount=§r
serp.biome_evolve=§b進化させる
serp.biome_forestc=§r 
serp.biome_forestr=§r 
serp.biome_forests=§r 
serp.biome_foresth=§r 
serp.biome_forestu=§r 
serp.biome_forestl=§r 
serp.biome_=聖鈴図鑑
serp.biome_empty=聖鈴図鑑
stats.0=なし
stats.1=攻撃
stats.2=防御
stats.3=特攻
stats.4=特防
stats.5=素早さ
behavior.neutral=このようにステータスが変化します

nature.1=§c素早さ上昇§b防御ダウン§r
nature.2=§c特防上昇§b防御ダウン§r
nature.3=§c防御上昇§b特防ダウン§r
nature.4=§c特攻上昇§b素早さダウン§r
nature.5=§c防御上昇§b素早さダウン§r
nature.6=§c特攻上昇§b防御ダウン§r
nature.7=§c攻撃上昇§b素早さダウン§r
nature.8=§6すなお§f
nature.9=§c素早さ上昇§b攻撃ダウン§r
nature.10=§6すなお§r
nature.11=§c防御上昇§b特攻ダウン§r
nature.12=§c特防上昇§b特攻ダウン§r
nature.13=§c特防上昇§b素早さダウン§r
nature.14=§c特攻上昇§b攻撃ダウン§r
nature.15=§c特防上昇§b攻撃ダウン§r
nature.16=§c素早さ上昇§b特攻ダウン§r
nature.17=§6すなお§r
nature.18=§c攻撃上昇§b防御ダウン§r
nature.19=§c防御上昇§b攻撃ダウン§r
nature.20=§6すなお§r
nature.21=§c特攻上昇§b特防ダウン§r
nature.22=§c攻撃上昇§b特攻ダウン§r
nature.23=§c素早さ上昇§b特防ダウン§r
nature.24=§c攻撃上昇§b特防ダウン§r
nature.25=§aポケリエバッジ§r


serp.biome=§r
serp.getting=§r
type.0= 
type.1=§aむし§r
type.2=§8あく§r
type.3=§3ドラゴン§r
type.4=§eでんき§r
type.5=§dフェアリー§r
type.6=§4かくとう§r
type.7=§cほのお§r
type.8=§bひこう§r
type.9=§5ゴースト§r
type.10=§2くさ§r
type.11=§6じめん§r
type.12=§bこおり§r
type.13=§fノーマル§r
type.14=§5どく§r
type.15=§dエスパー§r
type.16=§4いわ§r
type.17=§fはがね§r
type.18=§bみず§r
type.19=§aサウンド§r
type.20=§gシャイン§r
type.21=オリジナル
type.22=オリジナル
type.23=オリジナル
type.24=オリジナル
type.25=オリジナル

serp.evolve=進化させる
attack.class_1=物理技
attack.class_2=特殊技
attack.class_3=変化技
attack.class_4=物理技
attack.class_5=特殊技
attack.class_7=物理技
attack.class_6=特殊技
combat.failed=当たらなかった！
ccmbat.cant_change_status=状態異常になった！
store.body_buy=商品を選んでください
serp.players.body=プレイヤーを選んでください

attack_info.1=するどいツメやカマで きりつけてこうげきする じぶんの こうげき があがる。
attack_info.2=ツノや爪で相手を突き刺す。この攻撃で相手を倒すと攻撃が上がる。
attack_info.3=いきおいよく しゅうげきし たまにあいてを こんらんにさせる。
attack_info.4=めにもとまらないはやさで とつげきする
attack_info.5=相手に飛びついて攻撃する。相手の素早さを下げる。
attack_info.6=相手に飛びかかって攻撃する。相手の攻撃を下げる。
attack_info.7=きゅうけつして攻撃。与えたダメージの半分回復する。
attack_info.8=勢いよく噛み付いて攻撃、与えたダメージ分回復する。
attack_info.9=硬くて りっぱな つので おもいっきり 相手を 突き刺して 攻撃する
attack_info.10=めにもとまらぬ ものすごいはやさで あいてをつきさす。
attack_info.11=抵抗して攻撃する。相手の特攻をがくっと下げる。
attack_info.12=銀色の颮をおこして攻撃する。たまに自分の全能力が上がる。
attack_info.13=バグのような音のノイズをおこして攻撃する。
attack_info.14=しもべを よびだして じぶんの からだに おおい つかせる。ぼうぎょと とくぼうを あげることが できる。
attack_info.15=いとをはいて、相手の素早さを2段階下げる。
attack_info.16=しんぴてきで うつくしい まいを かろやかに おどる。 じぶんの とくこうと とくぼうと すばやさを あげる。
attack_info.17=相手の目の前を飛行し撹乱させて攻撃。たまに混乱にさせる。
attack_info.18=彼岸と此岸の岸辺から永遠に君を想う。翔音で～す! 
attack_info.21=そのターンに あいてが すでに ダメージを うけて いたら わざの いりょくは 2ばいに なる。
attack_info.22=相手を叩き落とすように叩いて攻撃。相手が持ち物を持っていた場合は威力が1.5倍になり持ち物を落とす。
attack_info.23=爪などで切り裂いて攻撃。
attack_info.24=噛み付いて攻撃。まれに怯ませる。
attack_info.25=するどい はで あいてを かみくだいて こうげきする。あいての ぼうぎょを さげることが ある。
attack_info.26=全身全霊で攻撃して 相手を ぶち壊す。 自分の 防御と 特防が さがる。
attack_info.27=ないしょばなしを することで 相手の 集中力を 失わせ 相手の 特攻を がくんと さげる。
attack_info.28=じゃあくなきばであいてにかみつく。あいてのぼうぎょととくぼうをさげる。
attack_info.29=PPがすくないが あいてより さきに こうげき できる。
attack_info.30=ためこんで 攻撃する。 相手より あとに 攻撃できると 技の 威力は 2倍に なる。
attack_info.31=騒ぎ立てて攻撃。相手の特攻を下げる。
attack_info.32= 体から 悪意に みちた 恐ろしい オーラを 発する。相手を ひるませることが ある。
attack_info.33=悪意に満ちた力で相手を闇に落とし込み、相手をたまに混乱にさせる。
attack_info.34=爪をといで命中率をあげる。
attack_info.35=相手をおだてて攻撃を上げて、さらに混乱にする。
attack_info.36=邪悪な声で相手を攻撃。優先度+1
attack_info.37=邪悪な力を集め、相手の生気を吸い取る。与えたダメージの半分回復する。
attack_info.38=悪いことを 考えて 頭を 活性化させる。自分の 特攻を ぐーんと あげる。
attack_info.39=魔物のような咆哮で攻撃。与えたダメージの33%、自分も受ける。
attack_info.40=暗闇で包み込みこんで攻撃、自分の命中が下がる。
attack_info.41=しっぽを叩きつけて攻撃。相手の攻撃を下げる。
attack_info.42=するどく とがった きょだいな ツメで あいてを きりさいて こうげきする。
attack_info.43=激怒して攻撃する。たまに混乱する。
attack_info.44=すさまじい 殺気で 威圧しながら 体当たりする。 相手を ひるませることが ある。
attack_info.45=DINOSWORD!!周りの岩や骨などで剣を作り攻撃、たまに怯ませる。
attack_info.46=全力で相手を爪で切りつけ、たまに怯ませる。
attack_info.47=素早い反射神経で相手よりも早く体当たりをする。
attack_info.48=ウロコを ぴゅっぴゅっして こうげきする。 2-5かいの あいだ れんぞくで だす。 すばやさが あがるが ぼうぎょが さがる。
attack_info.51=竜巻を起こし攻撃し、たまに怯ませる。
attack_info.52=ものすごい 息を 相手に 吹きつけて 攻撃する。 まひ状態に することが ある。
attack_info.53=天空から 隕石を 相手に 落とす。 使うと 反動で 自分の 特攻が がくっと さがる。
attack_info.54=龍の 波動を 相手に 吹きつけて 攻撃する。
attack_info.55=固定40ダメージを与える技。
attack_info.56=神秘的で 力強い 舞を 激しく おどる。 自分の 攻撃と 素早さを あげる。
attack_info.57=宇宙のエネルギーを吸い込みブレスを吐き出す。
attack_info.58=色んな属性を持つ不思議なブレスで攻撃。相手の特防を下げる。
attack_info.59=フィールドに満ちるエネルギーを集め、すべてを消し飛ばすほどの光線を放つ。
attack_info.61=雷の牙で相手に噛み付く。たまに相手を麻痺にする。
attack_info.62=電気を纏わせた拳で相手を攻撃する。たまに相手を麻痺にする。
attack_info.63=電気のエネルギーを身にまとい突撃する。自分も与えたダメージの25パーセント受ける。
attack_info.64=電気を まとい 相手に 突進して 攻撃する。 まひ状態に することが ある。
attack_info.65=電気を原動力にして、自分の素早さが上がる。
attack_info.66=粒子の力を使い、静電気を発生させながら相手に体当たりする。相手をたまに麻痺にする。
attack_info.67=強力な 電気を まといながら 相手に 突撃する。与えダメージの33パーセント自分も受ける。
attack_info.68=電気を刃のように飛ばして攻撃。急所に当たりやすい。
attack_info.69=へけw
attack_info.70=体内に蓄えた電気エネルギーを限界まで引き出し、強烈な電撃を放つ。
attack_info.71=電気を放ち攻撃する。たまに麻痺にさせる。
attack_info.72=10万ボルトを放ち攻撃する。たまに麻痺にさせる。
attack_info.73=雷を作り出し相手に放つ。たまに麻痺にさせる。
attack_info.74=電気の網を作り出し相手の素早さを下げる。
attack_info.75=電気を放電させて攻撃。たまに麻痺にさせる。
attack_info.76=周りにいる ポケモン 全員に ダメージ。 与えた ダメージの 半分を 自分が 回復する。
attack_info.77=超高速で相手に向かって電気を放つ。優先度+2。
attack_info.78=つよいきりゅうを　あいてにぶつけて　こうげきする。じぶんの　とくこうが　がくっとさがる。
attack_info.79=強力な雷雲を作り出して攻撃。たまに麻痺にして怯ませる。
attack_info.81=相手にじゃれつくついて攻撃。たまに相手の攻撃を下げる。
attack_info.82=食らうと くじけるほどの 勢いで 攻撃。 相手の 特攻を 下げる。
attack_info.83=不思議な力を爪にこめて引っ掻く。
attack_info.84=相手を夢中にさせるパンチを繰り出す。
attack_info.85=抱きついて攻撃。
attack_info.86=月の力をまといながら相手に突撃する。自分も与えたダメージの33パーセント受ける。
attack_info.87=かわいく みつめて 油断を 誘い 相手の 攻撃を がくっと さげる。
attack_info.88=相手に うさきとびで とびついて 攻撃する。 相手の 攻撃を がくっと さげる。
attack_info.91=キッスによって相手のHPをすいとる、与えたダメージの半分回復。
attack_info.92=ようせいのかぜをおこし攻撃。
attack_info.93=月のパワーを借りて相手を攻撃する。たまに相手の特攻を下げる。
attack_info.94=天使のように かわいく キスして 相手を 混乱させる。
attack_info.95=つぶらなひとみで 相手を みつめて 攻撃を さげる。 必ず 先制攻撃 できる。
attack_info.96=天使のような 歌声で 相手を 攻撃。 たまに 混乱の 状態に する。
attack_info.97=ふしぎなきりで　あいてをつつみこみ　こうげきする。
attack_info.98=不思議な魔法を使って、自分の素早さと命中を上げる。
attack_info.99=きりを　ばくはつさせて　あいてを　こうげきする。じぶんも　だめーじを　うける。
attack_info.101=鋭い チョップで 相手を たたいて 攻撃する。
attack_info.102=空に むかうような 高い アッパーで 相手を 突きあげて 攻撃する。
attack_info.103=相手に素早く連撃を繰り出し攻撃する。自分の防御と特防が下がる。
attack_info.104=チョップを 相手に たたきつけて 攻撃する。 急所に 当たりやすい。
attack_info.105=通常技。
attack_info.106=自分の素早さが下がる。
attack_info.107=目にも止まらぬ早いパンチを繰り出す。優先度+1
attack_info.108=ふんぬ
attack_info.109=力を ふりしぼり 攻撃する。自分の HPが 少ないほど 技の 威力は あがる。
attack_info.111=真空波を放つ。優先度+1
attack_info.112=波動弾を放つ、確実に命中する。
attack_info.113=気合を込めて波動を作り出して攻撃。
attack_info.114=体に 力を こめて 筋肉を ぶあつく することで 自分の 攻撃と 防御を あげる。
attack_info.115=集気を集めて強力な波動弾を作り出し攻撃するが、相手の攻撃と特攻を上げてしまう。
attack_info.116=【"ファイナルラウンド"】1度しか使えないが、自分の攻撃,防御,特攻,特防,素早さ,命中率を1段階上昇させる。
attack_info.117=波動の弾を、銃弾のように撃ち込んで攻撃。自分の命中率がたまに上がる。
attack_info.121=燃え盛る妖火を廻りに踊らせ 舞いながら前に突進する。自分の素早さが上がる。
attack_info.122=炎の拳で相手を攻撃する。たまにやけどにする。
attack_info.123=炎を まとって 突進する。自分も かなり ダメージを 受ける。やけど状態に することが ある。
attack_info.124=炎を纏った牙で噛み付いて、相手をたまにやけどにする。
attack_info.125=炎のキックで相手を攻撃。
attack_info.126=線香(先行)花火。ロケット花火のように相手に突撃する、優先度+2。
attack_info.127=妬みの力で強力な炎を作り攻撃。30パーセントで自分が混乱する。
attack_info.128=かじばのちからで ちからをふりしぼって  こうげきする。おこったも〜んだ！
attack_info.131=火の粉で相手を攻撃する。たまにやけどにする。
attack_info.132=火炎放射で相手を燃やし尽くす。たまにやけどにする。
attack_info.133=大の文字に炎を作り相手を攻撃する。たまにやけどにする。
attack_info.134=怪しく燃える魂を相手に放ち、やけどにさせる…
attack_info.135=当たると はじける 炎で 相手を 攻撃する。はじけた 炎は 隣の 相手にも ふりかかる。
attack_info.136=とても強い日差しで相手を攻撃する。攻撃後、天候がひでりになる。
attack_info.137=熱風を作り出し相手にダメージを与える。
attack_info.138=火災旋風を起こして攻撃する。自分がやけどになる。
attack_info.139=相手を追尾する炎を作り出す。相手の素早さが上がる。
attack_info.140=ぜんりょくのほのおをあいてにあびせてこうげきする。こうげきのあととくこうがぐーんとさがる。
attack_info.141=つついて攻撃。たまに混乱にさせる。
attack_info.142=軽やかに 相手を 攻撃する。自分が 道具を 持っていないとき 威力が2倍になる。
attack_info.143=翼をぶつけて攻撃する。
attack_info.144=羽を折りたたみ 低空飛行で突撃する。自分も与えたダメージの33パーセント受ける。
attack_info.145=ドリルのように鋭い嘴で攻撃。
attack_info.146=滑空して翼を当てて攻撃。たまに自分の命中が上がる。
attack_info.147=風の弾を作り出し、腕や体当たりなどで相手目掛けて飛ばす。たまに混乱にさせる。
attack_info.148=空から爪で切り裂いて攻撃。相手の命中を下げる。
attack_info.149=天空から急降下し、翼でぶつけて攻撃。自分の防御と特防が下がる。
attack_info.150=みんなの好きな雲って何かな？俺は積乱雲が好きやな。ぜひコメントで教えてね！
attack_info.151=風を起こして攻撃。相手を混乱にする。
attack_info.152=空も切り裂く空気の刃で攻撃する。たまに怯ませる。
attack_info.153=神風を起こして相手を攻撃。たまに混乱にさせる。
attack_info.154=鎌鼬を起こして相手を包むようにして攻撃。たまに怯ませる。
attack_info.155=ジェット気流を起こして相手に先制攻撃をする。
attack_info.156=激しい風を背後からを起こして相手を支配する。たまに相手を混乱にさせる。
attack_info.157=神へ起こる風で相手を攻撃する。自分の命中が1段階上がるが、混乱になる。
attack_info.158=強力な空気の波動を放って攻撃する、自分の素早さが低いほど威力が100から下がる(最小威力10)
attack_info.161=相手を舐めて嫌な気持ちにさせて精神攻撃。たまに麻痺をする。
attack_info.162=相手の影を使い背後から攻撃、優先度+1
attack_info.163=影から作ったツメで相手を切り裂き、急所に当たりやすい。さらに相手の回避率を下げる。
attack_info.164=影からパンチを放ち攻撃する。必ず命中し、相手の回避率をがくっとさげる。
attack_info.165=驚かして攻撃。
attack_info.166=命取りになるような強力な攻撃を繰り出す。与えたダメージの半分回復。
attack_info.168=強力な一閃で相手を斬る。自分が眠りになる。
attack_info.167=暗夜の翼をぶつけて攻撃。相手の回避率を下げる。
attack_info.169=マイケル？おーわーお！命中不安定なんてクソ喰らえだね！
attack_info.171=怪しい風を起こし相手を攻撃。たまに自分の全能力が上がる。
attack_info.172=無数の火の玉で攻撃して相手の特防をたまに下げる。
attack_info.173=黒い影の塊を投げつけ攻撃。相手の特防をたまに下げる。
attack_info.174=あやしいひかりを出して相手を混乱にさせる。
attack_info.175=相手が状態異常の場合、威力が2倍になる。たまに相手の特防を下げる。
attack_info.176=相手に乗り移り苦しませて攻撃。30パーセントで怯ませる。
attack_info.177=不思議な 黒魔術 を使い 攻撃。自分の防御・素早さ・回避率が下がり、自分の特攻・特防・命中率が1段階上がる。
attack_info.178=あの世の力を持った波動を放つ。相手をたまに毒にする。
attack_info.179=強い恨みや憎しみを力に変えて 相手を呪って攻撃する。
attack_info.180=ん、
attack_info.181=はっぱを あいてに あてて こうげきする。
attack_info.182=はっぱを とばして あいてを きりつけて こうげきする。 きゅうしょに あたりやすい。
attack_info.183=はっぱを つるぎのように あやつり あいてを きりつけて こうげきする。 きゅうしょに あたりやすい。
attack_info.184=ツタを硬化させて相手を叩いて攻撃。相手の攻撃を下げる。
attack_info.185=硬い 胴体を 相手に たたきつけて 攻撃する。自分も かなり ダメージを 受ける。
attack_info.186=草花を活性化させて狂い咲く。自分の攻撃が1段階上がる。
attack_info.187=草や木で輝く剣を作り出し斬る。自分の命中が下がる。
attack_info.188=くさわけ
attack_info.189=ぴゅっぴゅっ ゴーゴゴーだぜ
attack_info.191=ようぶんを すいとり こうげきする。 あいてに あたえた ダメージの はんぶんの HPを かいふくできる。
attack_info.192=ようぶんを すいとり こうげきする。 あいてに あたえた ダメージの はんぶんの HPを かいふくできる。
attack_info.193=自然の力を込めて、古代の咆哮で相手を攻撃する。使うと反動で特攻が1段階下がる。
attack_info.194=しぜんから あつめた いのちの ちからを はっしゃする。あいての とくぼうを さげることがある。
attack_info.195=フワフワの 綿毛で 自分の 体を 包みこんで 守る。防御と素早さを ぐーんと あげる。
attack_info.196=眠らせる鱗粉を使う。
attack_info.197=相手を追撃する葉っぱを飛ばして攻撃。必ず命中する。
attack_info.198=地面から蔦を伸ばして力を奪う。相手に与えたダメージの4分の3回復する。
attack_info.199=しぜんの エネルギーを あつめた しんぴてきな あらしをよぶ。自分の特攻が3段階下がる。
attack_info.200=くさタイプの攻撃相性を反対にして攻撃する。
attack_info.201=地面を揺らし相手を攻撃。相手の素早さを下げる。
attack_info.202=全身を 使って 相手に 猛アタックする。
attack_info.203=地震を引き起こし相手を攻撃。
attack_info.204=ドリルのように素早く相手に突撃して攻撃、優先度+1。
attack_info.205=爪や腕で地面を捲りあげて攻撃する。たまに相手の命中を下げる。
attack_info.206=牙で思いっきり噛み付いて攻撃。自分の防御が下がる。
attack_info.207=土を巻き上げて竜のしっぽのように叩きつけて攻撃する。
attack_info.208="いだてん"と読む。
attack_info.211=泥をかけて攻撃。
attack_info.212=泥をさらにかけて攻撃。
attack_info.213=泥で爆弾を作り攻撃。
attack_info.214=砂をかけて命中を下げる。
attack_info.215=熱々な砂をかけて攻撃する。たまにやけどにする。
attack_info.216=相手の 足下へ 大地の力を 放出する。相手の 特防を さげることが ある。
attack_info.217=大地の力を集めて、相手に衝撃波で攻撃する。自分の特攻と特防が下がる。
attack_info.218=不思議な力を持つキューブをつくり爆発させて攻撃。相手の攻撃 防御 特攻 特防がぐーんと 上がる。
attack_info.219=地底からエネルギーを吸い寄せ、特攻と特防を1段階上げる。素早さは1段階下がる。
attack_info.221=素早いこおりのつぶてを放つ、優先度+1。
attack_info.222=氷の力を持つキバで相手を攻撃する。たまに凍らせる。
attack_info.223=氷の力を持つ拳で相手を攻撃する。たまに凍らせる。
attack_info.224=相手の上から氷柱を落とし攻撃する、たまに怯ませる。
attack_info.225=冷気を爪に纏わせながら、相手を斬り裂いて攻撃。たまに怯ませる。
attack_info.226=冷ややかなムードってたまにあるよね、あの時にこのみぞおちひややかパンチしたらぶっ殺すことできるわよ
attack_info.227=氷の槍を創り出して相手を突き刺す。たまに怯ませる。
attack_info.228=相手から 技を 受けていると その 相手に 対して 技の 威力が 2倍に なる。
attack_info.229=3回連続で 宇野昌磨を くりだして 攻撃する。 技が 当たるたびに 威力が20ずつ あがる。　
attack_info.231=冷たい 粉雪を 相手に 吹きつけて 攻撃する。 こおり状態に することが ある。
attack_info.232=凍てつく 冷気を 相手に 吹きつけて 攻撃する。相手の 素早さを さげる。
attack_info.233=氷のビームを相手に放ち攻撃する、たまに凍らせる。
attack_info.234=にじいろの ビームを 相手に 発射して 攻撃する。攻撃を さげる ことが ある。
attack_info.235=激しい 吹雪を 相手に 吹きつけて 攻撃する。こおり状態に することが ある。
attack_info.236=強力なブリザードを起こして攻撃。自分は状態異常〈こおり〉になる。
attack_info.237=力をふりしぼり猛吹雪を起こして攻撃する。自分も与えたダメージの半分受ける。
attack_info.241=たいあたりで攻撃する。
attack_info.242=ひっかいて攻撃する。
attack_info.243=目にも 留まらぬ ものすごい 速さで 相手に 突進して 攻撃する。優先度+2。
attack_info.244=かわいく あまえながら あいてに ちかづき もっている どうぐを うばう。
attack_info.245=1ターンめに あたまを ひっこめて ぼうぎょを あげる。2ターンめに あいてを こうげきする。
attack_info.246=相手のHPが1残るように攻撃する。
attack_info.247=カマや ツメなどで 相手を 切りつけて 攻撃する。
attack_info.248=命を 懸けて 相手に 突進して 攻撃する。 自分も かなり ダメージを 受ける。
attack_info.249=しっぽを振り回して相手を攻撃する。
attack_info.250=ちからを こめた パンチで あいてを こうげきする。自分の攻撃が下がる。
attack_info.251=大きな 爆発で 自分の 周りに いるものを 攻撃する。使ったあとに ひんしに なる。
attack_info.252=星を相手に命中させる。必ず命中する。
attack_info.253=強い 光線を 相手に 発射して 攻撃する。次の ターンは 動けなくなる。
attack_info.254=切り札は"ハートのエース"。自分の命中が上がる。
attack_info.255=大きな声を出して攻撃する。
attack_info.256=振動する声を出して攻撃。必ず命中する。
attack_info.257=防御を下げる。
attack_info.258=攻撃を下げる。
attack_info.259=戦いの舞を 激しく おどって 気合を 高める。自分の 攻撃を ぐーんと あげる。
attack_info.261=毒の ある キバで 相手に かみついて 攻撃する。 猛毒を おわせる ことが ある。
attack_info.262=毒に染った触手や腕で相手を突き刺す。たまに毒にする。
attack_info.263=汚いゴミを相手になげつけ攻撃、たまに毒にする。
attack_info.264=毒気のあるシッポで相手を攻撃する。たまに毒にする。
attack_info.265=猛毒のある危険な葉っぱで相手を攻撃する。たまに相手を毒にする。
attack_info.266=毒の 刃で 相手を 切り裂く。 毒状態に することが あり 急所にも 当たりやすい。
attack_info.267=毒に染った触手や腕で相手を何度も突き刺す。自分が混乱になる。
attack_info.271=相手を とかす 液体を 吐きだして 攻撃する。相手の 特防を がくっと さげる。
attack_info.272=特殊な 毒液を 浴びせかける。毒状態の 相手には 威力が 2倍に なる。
attack_info.273=毒の爆弾を投げつけて攻撃。たまに毒にする。
attack_info.274=相手を猛毒にする。
attack_info.275=毒の粉を振りまいて相手を毒にする。
attack_info.276=毒ガスを放ち相手を必ず毒にする。
attack_info.277=BADな毒で相手を攻撃する。
attack_info.278=混沌した猛毒の波動を放つ。攻撃後、自分が毒になる。
attack_info.281=実体化させた 心の 刃で 相手を 切り裂く。 急所に 当たりやすい。
attack_info.282=思念の 力を 額に 集めて 攻撃する。 相手を ひるませることが ある。
attack_info.283=かわいい しぐさで 油断させて 強烈な 一撃を 浴びせる。相手を ひるませることが ある。
attack_info.284=サイコパワーで かみついて 相手を 攻撃する。 ひかりのかべや リフレクター なども 破壊できる。
attack_info.285=冬の 雲1つない 綺麗な 日差しで 相手を 攻撃する。たまに怯ませる。
attack_info.286=相手をノックバックさせるような勢いで拳で叩きつける。相手の防御が下がる。
attack_info.287=自分の反射神経を犠牲にサイコパワーで殴りつける。相手は素早さが下がる。
attack_info.291=ねんりきをつかい攻撃、相手をたまに混乱にさせる。
attack_info.292=強い念力で相手を攻撃、たまに相手の特防を下げる。
attack_info.293=相手をねむりにする
attack_info.294=不思議な 念波を 実体化して 相手を 攻撃する。 相手の防御をがくっと下げる。
attack_info.295="占星(先制)術"不思議な念力を使い優先度+1で攻撃、さらに相手の命中を確実に下げる。
attack_info.296="みかぐら" 自分のすばやさを1段階あげる。
attack_info.297=テレポートし、伝説のポケモンが居る聖域へワープできる。
attack_info.298=頭を からにして 一瞬 なにかを 忘れることで 自分の 特防を ぐーんと あげる。
attack_info.299=静かに 精神を 統一し 心を 鎮めることで 自分の 特攻と 特防を あげる。
attack_info.300=おお。あくタイプとくさタイプにも抜群になる。
attack_info.301=岩を落として攻撃、たまに怯ませる。
attack_info.302=岩で逃げ場をなくし相手の素早さを下げる。
attack_info.303=とがった 岩を 相手に 突き刺して 攻撃する。急所に 当たりやすい。
attack_info.304=命を 懸けて こん身の 力で 相手に 突撃 する。 自分も与えたダメージの半分受ける。
attack_info.305=大きな 岩を 激しく ぶつけて 攻撃する。相手を ひるませることが ある。
attack_info.306=相手のHPが満タンでは無い時、威力が1.2倍になる。
attack_info.307=下から岩を突き上げて攻撃。
attack_info.308=強力な彗星を落として攻撃する。たまに怯ませる。
attack_info.309=硬い 岩石を 相手に ぴゅっぴゅっと発射して 攻撃する。 2-5回の 間 連続で だす。
attack_info.311=原子のパワーで岩を作り出し攻撃、たまに自分の全能力が上がる。
attack_info.312=宝石のように きらめく 光を 発射して 相手を 攻撃する。
attack_info.313=1ターン目に特攻をぐーんとあげて、2ターン目に攻撃。
attack_info.314=眠っていた古代の力を活性化させて素早さを3段階上昇させる。
attack_info.315=宝石同士を衝突させて 溜まった エネルギー光線で 相手を 攻撃する。
attack_info.316=おおむかしの ちからをもつ ブレスでこうげき。必ず特攻が上がる。
attack_info.317=発射に時間がかかるが強力なブレスを吐きつける。
attack_info.318=相手の 周りに 無数の 岩を 浮かべて 交代で でてきた 相手の ポケモンに ダメージを 与える。
attack_info.321=金属のような硬い爪で相手をひっかく、たまに自分の攻撃が上がる。
attack_info.322=とがった つので 相手を 突き刺して 攻撃する。 攻撃は 必ず 命中する。
attack_info.323=金属のように硬いしっぽで相手を攻撃、たまに相手の防御を下げる。
attack_info.324=弾丸の ような 速くて 硬い パンチを 相手に くりだす。 必ず 先制攻撃 できる。
attack_info.325=鋼の ような 硬い 頭で 攻撃する。相手を ひるませることが ある。
attack_info.326=翼を鋼のように硬くして相手を攻撃、たまに防御を下げる。
attack_info.327=すい星の ごとく パンチを くりだして 相手を 攻撃する。 自分の 攻撃が あがることが ある。
attack_info.328=鉄の破片で剣を作り出し斬って攻撃。
attack_info.329=鋼の柵を作り出して剣のように切り裂く。自分の防御が下がる。
attack_info.330=相手の攻撃が低いほど威力が下がる(最小威力:20)
attack_info.331=磨きあげられた 体から せん光の 力を 相手に 放つ。命中率を さげることが ある。
attack_info.332=金属の塊を放ち攻撃する。相手の特防をたまに下げる。
attack_info.333=ぜんしんのちからをこうせんにかえてあいてをこうげきする。つかったあとじぶんもおおきなだめーじをうける。
attack_info.334=大きな金属の弾を相手にぶつけて攻撃。相手の攻撃と特攻が上がる。
attack_info.335=磁力の線を作り出し攻撃。
attack_info.336=§b星を降らせて攻撃する。自分の防御と特防が上がる。
attack_info.337=皮膚を 鉄のように 硬くする ことで 自分の 防御を ぐーんと あげる。
attack_info.338=はくぎんに ひかる ひかりをいってんに あつめて ひかりをはなつ。
attack_info.341=目にも 留まらぬ ものすごい 速さで 相手に つっこむ。優先度+1。
attack_info.342=すごい 勢いで 相手に つっこむ。 相手を ひるませることが ある。
attack_info.343=激しく荒れくるう波のように 大きなしっぽをふって 相手を攻撃する。
attack_info.344=水の 力で 相手に ぶつかって 攻撃する。相手の 防御を さげる ことがある。
attack_info.345=水と 共に 相手へ 体当する。相手の 特攻を さげる。
attack_info.346=水を まといつつ 全身で 相手に ぶつかるが 自分も かなりの ダメージ を受ける。
attack_info.347=深海の力を借りて水と共に体当たりをする。自分の攻撃がたまに上がる。
attack_info.348=獲物を狩りつくすような、鋭い牙で噛み付く。防御と特防が下がる。
attack_info.351=無数の 泡を 相手に 吹きかけて 攻撃する。相手の 素早さを さげることが ある。
attack_info.352=水の 振動を 相手に 与えて 攻撃する。 相手を 混乱させることが ある。
attack_info.353=大量の水を激しい勢いで 相手に発射して攻撃する。
attack_info.354=帯電した水を相手に発射して攻撃する、たまに相手を麻痺にさせる。
attack_info.355=大きな 波で 自分の 周りに いるものを 攻撃する。
attack_info.356=海の加護を借りて、防御と特防をあげる。
attack_info.357=濁った 水を 相手に 発射して 攻撃する。 命中率を さげることが ある。
attack_info.358=激しい雨を降らせて攻撃し、天候を雨に変える。
attack_info.359=みずでできたしゅりけんをれんぞくでなげつけてこうげきする。かならずせんせいしてこうげきできる。
attack_info.361=音の衝撃波をぶつけて攻撃。
attack_info.362=音符を実態化させて攻撃する。
attack_info.363=低音を響かせて攻撃する。
attack_info.364=激しい低音を響かせて攻撃。必ず当たる。
attack_info.365=気分が明るくなる低音を響かせて攻撃。音色が染み入り与えたダメージの半分回復する。
attack_info.366=恐怖を感じるような音を響かせて攻撃。自分も与えたダメージの半分受ける。
attack_info.367=リズムよく ビートを奏でて攻撃。 2-5回の 間 連続で だす。
attack_info.371=ゆっくりとしたサウンドを響かせて攻撃。
attack_info.372=メロディを響かせて攻撃。
attack_info.373=美しい歌声で相手を攻撃する。
attack_info.374=様々な音の音色で自分を鼓舞して攻撃と特攻をぐーんとあげる。
attack_info.375=大きな騒音で相手を攻撃する。
attack_info.376=完璧な音色を奏でて攻撃する。自分の特攻が必ず上がる。
attack_info.377=アイ 愛、スクリ～ム SCREAM 叫びましょ(スクリーム！ アイスクリーム！）OK! アイ 愛、スクリ～ム！SCREAM 叫びましょ（スクリーム！　アイスクリーム！)
attack_info.381=聖なるキバで噛み付いて攻撃。たまに相手を混乱にさせ、怯ませる。
attack_info.382=毛やトゲなどを聖なる力で包み込んで発射して攻撃。たまに相手の回避を下げる。
attack_info.383=眩しい光で相手を目くらませている間に攻撃する。たまに相手の命中を下げる。
attack_info.384=必ず当たる正義の鉄槌を下す。攻撃がガクッと下がる。
attack_info.385=不思議なブロック状の光源をぶつけて攻撃。相手が交代するまで、相手の受けるダメージを2〜3倍にする。
attack_info.386=暗くて美しい光を爪に纏わせて切り裂く。相手の防御が下がる。
attack_info.387=光の刃を飛ばして攻撃。自分の攻撃が上がる。
attack_info.388=点滅する光を浴びせて 攻撃する。 2-5回の 間 連続で だし 威力は高いが 相手に命中する度に 自分の命中率が下がっていく。
attack_info.389=『Radiant Zenith』天界から剣を呼び、相手を攻撃する。たまに相手の防御と素早さを下げる。
attack_info.391=スポットライトを上から当てて攻撃。必ず当たり、たまに相手の命中を下げる。
attack_info.392=サーチライトで照らして攻撃。相手の特防を下げる。
attack_info.393=眩しい光で照らして攻撃する。たまに相手の命中を下げる。
attack_info.394=強力な光を体から放って攻撃する。自分の防御と特防が下がる。
attack_info.395=雷雲を作りだして必ず命中する攻撃を放つ。相手が交代するまで、相手の全てのわざの命中率を20〜60パーセントランダムで下げる。
attack_info.396=弾ける閃光を飛ばして攻撃、自分も20パーセントダメージを受ける。
attack_info.397=冬の雪を溶かす優しいひかりで相手を攻撃する。与えたダメージの25パーセント回復する。
attack_info.398=眩しい暗闇を放って攻撃。自分の命中率が下がる。
attack_info.401=ながい　しっぽや てあしを　つかい あいてを はたいて　こうげきする。
attack_info.402=おおきな　からだを あいてに おもいきり たたきつけて　こうげきする。
すattack_info.403=するどい　つので あいてを つきさして こうげきする。
るattack_info.404=いきおいよく あいてに とっしんして こうげきする。 じぶんも　すこし ダメージを　うける
attack_info.405=めにも とまらぬ すばやさで あいてに とびかかって　こうげきする。
attack_info.406=するどい ツメや カマなどで あいてを きりさいて　こうげきする。
attack_info.407=するどい ツメで あいてを きりさいて　こうげきする。 あいての　ぼうぎょを さげることが　ある。
attack_info.408=グソクムシャの専用技。あいてをつめで きりさいて うちとる。『いあい』をつかっていないと しっぱいする。
attack_info.409=グソクムシャの専用技。しんけいを とぎすませて あいての うごきを みきる。すべての こうげきわざが あいてのかいひりつや じぶんのめいちゅうに かかわらず かならず あたるようになる。
attack_info.414=しんけいを とぎすませて きゅうしょに あたりやすくする。
attack_info.411=あいてに しょうじゅんを あわせることで つぎの　こうげきが かならず　あたる。
attack_info.412=こわい かおで あいてを　おどろかせ すばやさを がくっと　さげる。
attack_info.413=からだを するどく とぎすませて じぶんの　こうげきを あげる。
attack_info.414=しんけいを とぎすませて きゅうしょに あたりやすくする。
attack_info.415=みみを ふさぎたくなる いやな　おとを　だして あいての　ぼうぎょを 　さげる。
attack_info.416=おめめくるくる 
attack_info.417=からだを くすぐって わらわせることで あいての　こうげきと すばやさを　さげる。
attack_info.418=３しゅるいの こうげきを　あいてに ぶつけて　こうげきする。 やけどや　まひ こおりじょうたいに することが　ある。
attack_info.441=ふしぎな　かせいの エネルギーを　あたえる。みかた　ぜんいんの　こうげきを あげる。
attack_info.451=せいを こめて はどうを ほしのように あつめて こうげきする。 あいての とくぼうを ガクンと さげしてまう。
attack_info.452=まわしがさ のように かいてんしながら あいてに とつげきする。じぶんの すばやさが ぐーんとあがる。
attack_info.453=とてもきょうりょくな どくのきりを あいてぜんたいに ほうしゅつする。もうどくじょうたいに することがある。
attack_info.454=こくうの ランスを つかい あいてを つきさして こうげきする。あいてにあたえた ダメージの4分の3 かいふくする。 
attack_info.455=いのちの おとで みかたぜんたいの とくこう とくぼう すばやさ をあげる。
attack_info.461=どとうの パンチで 相手を なぐりつけて 攻撃する。2-5回の 間 連続で だす。
attack_info.471=全てのカードが揃った時 それは終わりではなく始まり 終わりへの始まり
attack_info.472=念能力で 弾を 無数に作り出し  攻撃する。2-6回の 間 連続で だす。
attack_info.473=相手の 力を 利用する。 戦っている 相手の 攻撃が 高いほど ダメージが あがる。
attack_info.474=キャンディ&チョコレート なんかよりも刺激的\nモンスター&ゴースト だって\nとろけちゃうくらいに\nずっとずっとキミを縛る恋の罠\nもっともっと欲しくなるでしょ?
attack_info.475=リフレクターを貼ると そうですね
attack_info.476=ひかりのかべなんだって、美味しーーー！
attack_info.477=バトンタッチ！
attack_info.478=きりをはらい ぜんいんの リフレクターや ひかりのかべを とりのぞく
attack_info.479=中指を立てて〜 せ〜の、FUCK！
attack_info.480=煉獄の炎で 相手を包み込んで 攻撃。
attack_info.481=自らの罪を善行をして滅ぼす技やな。ちなみに罪を滅ぼしてないと失敗するから、BANギリギリのイエローカードのやつは善行をしてちゃんと償えよ、ぶっ飛ばすぞ。
attack_info.482=七色の虹のようなレーザーを飛ばして攻撃する。攻撃後、自分のタイプがフェティシュに説明飽きた
attack_info.483=使用後、自分はみずタイプわざを使えなくなる。
attack_info.484=使用後、自分はくさタイプわざを使えなくなる。
attack_info.485=あいてを おこらせる。3ターンの あいだ あいては ダメージを あたえる わざしか だせなく なる。
attack_info.486=草
attack_info.487=chocoはやっぱり爪を入れるよね？
attack_info.488=最高のサイコパステスト、いや！サイコウパステストか！
attack_info.489=チョコに髪の毛を入れて食わせる感覚最高！
attack_info.490=メロディフィールドって名前いいよネ！さいこうになうでいけてるってかんぢやな！！
attack_info.491=うぼぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁぁ
attack_info.492=アンコールでド！ド！ド！歌ってくれ！！！！これだけは最初から圧倒的に人気だった記憶がある、みらくらぱーく！最初の曲。曲のつくりが王道の、しかもひと昔前のアイドル系アニソンといった具合。だからこそ初見から評価が高かったのかな、と思っている。ただ、初見の頃から一枚岩ではない楽曲でもあった。というのも、主にBメロで「昔ばなしに載っけてよ」等、なんとなくメッセージ性の強い歌詞や演出がちらほら見られた。また、みらくらぱーく！自体が2023年4月時点では両メンバーともに入部しておらず、明らかに「何かがある」ユニットとされていた。「ド！ド！ド！という曲は、後に泣き曲になるんじゃないか」という予想を、当時の自分か誰かが言っていたりしていたはず。まさか8月活動記録で、この曲のポジションと歌詞と物語であそこまで号泣することになるとは当時は思わなかったが。そもそもハンデありのノンフィクションが、るりちゃんだけじゃなくてめぐちゃんにも掛かってた、ってだけであそこまでしんどくなるとは思わなかったが。いちばん泣いたド！ド！ド！は103期8月度Fes×LIVEだったと未だに思う。その8月時点でド！ド！ド！が文脈として完成したかといえば、寧ろこれがスタート地点だったことこそが、この楽曲のポテンシャルを語るに相応しい。勿論ライブでは常に冒頭のフォーメーション=優勝確定演出として、またCメロ鬼退治パートは様々な公演でアレンジが加わることとなる。コールもmixもクラップも、ライブシーンのみならずアニクラシーンでも進化をし続け、何なら「Kアリバーのドンペリ」に関しては未だ悪名(？)として名高い。ジツは2024年になるまで意味不アイアイ(もう1回！のアレ)は殆ど定着していなかったりしてる。楽曲の文脈や情報のところでいくと、flowers*では2番からめぐちゃんが歌詞を書き足した話になっていたり。BANG YOU グラビティと(リアルでの)作詞作曲編曲が同じ人で構成されてたり。3rdライブみらくらぱーく！で急に104期Verが披露されて、かつ幕間で姫芽ちゃんの葛藤を交えた事実上の活動記録が披露されたり。歌詞に関しては、るりちゃんメインの歌詞かと思えばジツはるりめぐだった、というのはさっき書いた通り。作詞メインはめぐちゃんっぽさある(し、みらぱ！のアイドルっぽいアップテンポはだいたいめぐちゃん主導と考察してる)が、フレ！フレ！とチアーな感じはるりちゃん案に見えたりしてる。隅から隅まで103期みらくらぱーく！(るりめぐみらくらぱーく！……？)で構成されている。蓮ノ空オタクアンセム楽曲、という顔つきをしつつも様々な物語を引き連れてきた、まさしくみらくらぱーく！伝説に相応しき1曲目だと思う。てか、ここまで約束された勝利の楽曲を的確に作った作曲陣どれだけ凄いんだ本当に。こわい。個人的なこの楽曲の泣きどころは、初見、103期8月度活動記録→Fes×LIVE、3rdみらぱDay1、卒業公演だったと勝手に思ってる。6th辺りに久々披露されても、来るものがありそうな気がしてる。楽しみ。
attack_info.493=空蝉、これ漢字な。漢字でGOのLv4で出てくるから覚えておけ。
attack_info.494=エリミネーターはバイオハザード0のクリーチャーなんよwww、あなんよ使うやつは死ねなー？
attack_info.495=提案者:Rowlet5320 提案者のクソ寒くておもんないコメント「なんなんだあの波紋は！？波紋の連鎖でその野望を断ち切ってやる！波紋！波紋疾走連鎖ァァァァァァ！！！！！！！！！！」本来の効果:相手の場にリプループラグを設置して、交代で出てきたポケモンに相手の最大HP1/3のダメージを与え、その後リプループラグは消滅する。\nでんき・じめんタイプには効果がない\nむし・はがねタイプは受けるダメージが少し増える
attack_info.496=やっべぇwww風止まんねえんだけどwwwwうけるw
attack_info.497=ググレカス
attack_info.498=「白衣の天使が！あなたを訪ねて来ましたよ！」\nトリニティ総合学園の1年生で救護騎士団の一員。明るい性格の元気娘。患者を見つけると大騒ぎして事態を混乱させてしまったり、ちょっと抜けているところはあるものの、基本的には前向き。\n好きな花は彼女の苗字と同じ名前である「アサガオ」。\n彼女に世話してもらった患者は不思議なことに、どんな病気でもたちまち治り、元気になるのだとか…。
attack_info.499=めんどいから説明パス
attack_info.500=敵全体に闇属性の攻撃。威力は強力。って90やないかーい！闇ってなんやねんパズ〇ドラかお前
attack_info.501=ハッサムへジュナイパーはインファイトを透かせますが、ジュナイパーの火力が低いので、はねやすめで受け切られて剣舞の起点にされてしまいがちです。
attack_info.502=アローラキュウコンナイトはキナンシティにあるよお！？探してカス
attack_info.503=雨やめてね
attack_info.504=だいちの力を感じるのだ

attack_info.2019=ちょっとお！重いっすよ！

variant.0= 
variant.1=
variant.2=
variant.3=
variant.4=
variant.5=

entity.pokemon:p1.name=アルイテール
entity.pokemon:p2.name=ニ竜
entity.pokemon:p3.name=ノウ竜
entity.pokemon:p4.name=隠れ星
entity.pokemon:p5.name=イチバン星
entity.pokemon:p6.name=イットウ星
entity.pokemon:p7.name=スイ虫
entity.pokemon:p8.name=カイ虫
entity.pokemon:p9.name=シグレ雨衣
entity.pokemon:p10.name=バタピー
entity.pokemon:p11.name=ジャネガブーン
entity.pokemon:p12.name=ブツ・ブツ
entity.pokemon:p13.name=ホケキョ
entity.pokemon:p14.name=トリドリドリ
entity.pokemon:p15.name=ガルーダ
entity.pokemon:p16.name=ナイチンゲール
entity.pokemon:p17.name=アッパレス
entity.pokemon:p18.name=ストンビルダー
entity.pokemon:p19.name=ビリビリ魔人
entity.pokemon:p20.name=ヤヴァンパイア
entity.pokemon:p21.name=イビルーラー
entity.pokemon:p22.name=エンペランド
entity.pokemon:p23.name=ホールロッグ
entity.pokemon:p24.name=黄泉ガエル
entity.pokemon:p25.name=レロレロレロ
entity.pokemon:p26.name=グルグルグル
entity.pokemon:p27.name=ドクボックス
entity.pokemon:p28.name=アチボックス
entity.pokemon:p29.name=チューハイ
entity.pokemon:p30.name=魔女っ子チュー子
entity.pokemon:p31.name=鹿目まちゅか
entity.pokemon:p32.name=ブシドン
entity.pokemon:p33.name=ジゴクバッグ
entity.pokemon:p34.name=凶ノメバッグ
entity.pokemon:p35.name=シンノスケ
entity.pokemon:p36.name=プラネロボボ
entity.pokemon:p37.name=カゲノスケ
entity.pokemon:p38.name=チグハグルマ
entity.pokemon:p39.name=サクガンドス
entity.pokemon:p40.name=ミストレイン
entity.pokemon:p41.name=オヤサイサン
entity.pokemon:p42.name=ブルブドウ
entity.pokemon:p43.name=トマティーナ
entity.pokemon:p44.name=イティーゴ
entity.pokemon:p45.name=マジロウ
entity.pokemon:p46.name=オドッテヨウ
entity.pokemon:p47.name=返り血ダヨウ
entity.pokemon:p48.name=へアッ
entity.pokemon:p49.name=シュワッチ
entity.pokemon:p50.name=パレスヘイアン
entity.pokemon:p51.name=ココログサ
entity.pokemon:p52.name=コゴゴトネ
entity.pokemon:p53.name=人喰い草
entity.pokemon:p54.name=オデュッセイア
entity.pokemon:p55.name=ポコカリ
entity.pokemon:p56.name=オクトレイ
entity.pokemon:p57.name=グレイア
entity.pokemon:p58.name=リ・ボーン
entity.pokemon:p59.name=サムイ象
entity.pokemon:p60.name=ガマンモス
entity.pokemon:p61.name=プレファント
entity.pokemon:p62.name=ルリッシュ
entity.pokemon:p63.name=ビッカルアー
entity.pokemon:p64.name=ゲンショキザミ
entity.pokemon:p65.name=ズンドコズンドコ
entity.pokemon:p66.name=ズンドコイェイ
entity.pokemon:p67.name=邪魔蛙
entity.pokemon:p68.name=甘蛙
entity.pokemon:p69.name=ラブリーストーン
entity.pokemon:p70.name=魔女の家
entity.pokemon:p71.name=ゆ〜れい
entity.pokemon:p72.name=ぼ〜れい
entity.pokemon:p73.name=バケカブリ
entity.pokemon:p74.name=キャンプキン
entity.pokemon:p75.name=パンプキング
entity.pokemon:p76.name=ぜっこう鳥
entity.pokemon:p77.name=難鳥
entity.pokemon:p78.name=ゼッコウ鳥
entity.pokemon:p79.name=地獄ミミズク
entity.pokemon:p80.name=メイドリル
entity.pokemon:p81.name=ノンストップ
entity.pokemon:p82.name=ノーマン
entity.pokemon:p83.name=マラコーダ
entity.pokemon:p84.name=アサギョ
entity.pokemon:p85.name=ディープル
entity.pokemon:p86.name=アビスオーク
entity.pokemon:p87.name=アカマジュ
entity.pokemon:p88.name=エルドボーン
entity.pokemon:p89.name=エリュシオン
entity.pokemon:p90.name=ハナミズチ
entity.pokemon:p91.name=カラスネーク
entity.pokemon:p92.name=やーめるん蛇
entity.pokemon:p93.name=オロチ
entity.pokemon:p94.name=ドバットン
entity.pokemon:p95.name=アリクロン
entity.pokemon:p96.name=アキクロン
entity.pokemon:p97.name=成長虫
entity.pokemon:p98.name=進化虫
entity.pokemon:p99.name=業竜
entity.pokemon:p100.name=ティターン
entity.pokemon:p101.name=ホウロウク
entity.pokemon:p102.name=サマヨーリュウ
entity.pokemon:p103.name=チェキ
entity.pokemon:p104.name=タマゴミャン
entity.pokemon:p105.name=サイクス
entity.pokemon:p106.name=ハスター
entity.pokemon:p107.name=ビリグマ
entity.pokemon:p108.name=クマフィア
entity.pokemon:p109.name=テラスリック
entity.pokemon:p110.name=煇喰らい
entity.pokemon:p111.name=アラクレ
entity.pokemon:p112.name=アザゴース
entity.pokemon:p113.name=クウヒナ
entity.pokemon:p114.name=ゲヘナ
entity.pokemon:p115.name=フリーカオス
entity.pokemon:p116.name=ゴキパッタ
entity.pokemon:p117.name=ステッピー
entity.pokemon:p118.name=トノッパー
entity.pokemon:p119.name=ドクッパー
entity.pokemon:p120.name=プーブー
entity.pokemon:p121.name=ジョウハニー
entity.pokemon:p122.name=ア熊
entity.pokemon:p123.name=ゴマくん
entity.pokemon:p124.name=ゴマちゃん
entity.pokemon:p125.name=ゴ父さん
entity.pokemon:p126.name=ゴママ
entity.pokemon:p127.name=ゴマ様
entity.pokemon:p128.name=ヘイア
entity.pokemon:p129.name=ランファ
entity.pokemon:p130.name=ファラン
entity.pokemon:p131.name=ノビノビ太
entity.pokemon:p132.name=レアノビノビ太
entity.pokemon:p133.name=パンケーシュン
entity.pokemon:p134.name=デストロアイ
entity.pokemon:p135.name=ヤクモシルム
entity.pokemon:p136.name=アンブディア
entity.pokemon:p137.name=火焔竜
entity.pokemon:p138.name=光竜
entity.pokemon:p139.name=アグレア
entity.pokemon:p140.name=アルタオーロ
entity.pokemon:p141.name=エネノア
entity.pokemon:p142.name=ディアシス
entity.pokemon:p143.name=フォノウ
entity.pokemon:p144.name=サタンマーク
entity.pokemon:p145.name=ノウムラサメ
entity.pokemon:p146.name=アスリィノア
entity.pokemon:p147.name=アスグラン
entity.pokemon:p148.name=フィンドエル
entity.pokemon:p149.name=プラナハンド
entity.pokemon:p150.name=オブザプラナ
entity.pokemon:p151.name=ジャドリス
entity.pokemon:p152.name=佩く刻之神


serp.main.tm_machine.list=ニックネーム変更

attack.378= §aレゾナンスクライ§r
attack.433= §bうたかたのアリア§r
attack.400= §gホーリーグレア§r
attack.434= §aアネモネルージュ§r
attack.456= §l轟鳴§r
attack_info.378=共鳴する鳴き声で相手を100パーセント怯ませる
attack_info.260=天賦付きのAoE。AoEながらダメージは8(12)と同じ無色0コスのスイフトストライクを上回る。第1ターンに処理したいミニオンの群れに対しては有効だが、単体敵、特に中盤以後はやや出力不足。すぐに処理できる低HPの敵がいない場合、初期手札を圧迫しスキルやパワーを引きづらくしてしまう可能性がある。ピックする際はバックパックやギャンブルチップ等で初期手札のカバーを行いたい。

attack_info.456=本当にクソうるさい声で、敵味方全体にダメージを与える。マジでうるさい。


